
STRINGS = GLOBAL.STRINGS.NAMES
	
	STRINGS.UNCOMPROMISING_RAT = "Rat" -- Maybe change the name with a pun with Robber or Raider, any idea ?
	STRINGS.UNCOMPROMISING_RATHOLD = "Burrow"
	STRINGS.GASMASK = "Gas Mask"
	STRINGS.WATER = "Rain"
	STRINGS.RAIN = "Rain"
	STRINGS.SPORECLOUD_TOAD = "Spore Cloud"
	STRINGS.MOCK_DRAGONFLY = "Dragonfly"
	STRINGS.SAND = "Sand"
	STRINGS.SANDHILL = "Sandy Pile"
	STRINGS.SNOWPILE = "Snow Pile"
	STRINGS.SNOWGOGGLES = "Puss Peepers"
	STRINGS.SPIDERQUEENCORPSE = "Spider Queen Corpse"
	STRINGS.RATPOISON = "Poison Jam"
	STRINGS.RATPOISONBOTTLE = "Poison Jam"
	STRINGS.LEECHSWARM = "Leech Swarm"
	STRINGS.LAITLEECH = "Lait Leech"
	STRINGS.SHOCKWORM = "Depths Eel"
	STRINGS.ZASPBERRY = "Zaspberry"
	STRINGS.SNOWMONG = "Abominamole"
