Assets = {
    -- Livingtree root attack custom art by @Advent (modded from poison birchnut roots)
    Asset("ANIM", "anim/tree_leaf_spike_lt.zip"),
    Asset("ANIM", "anim/frog_yellow_build.zip"),
	Asset("ANIM", "anim/acid_meter.zip"),
	Asset("ANIM", "anim/deerclops_ground_fx.zip"),
	Asset("ANIM", "anim/deerclopsfalling.zip"),
	Asset("ANIM", "anim/player_sneeze.zip"),
	Asset("ANIM", "anim/hat_gasmask.zip"),
	Asset("ANIM", "anim/hat_snowgoggles.zip"),
	
	Asset("ATLAS", "images/fx4.xml"),
	Asset("IMAGE", "images/fx4.tex"),
	Asset("ATLAS", "images/fx5.xml"),
	Asset("IMAGE", "images/fx5.tex"),
	Asset("ATLAS", "images/inventoryimages/gasmask.xml"),
	Asset("IMAGE", "images/inventoryimages/gasmask.tex"),
	Asset("ATLAS", "images/inventoryimages/sand.xml"),
	Asset("IMAGE", "images/inventoryimages/sand.tex"),
	Asset("ATLAS", "images/inventoryimages/snowgoggles.xml"),
	Asset("IMAGE", "images/inventoryimages/snowgoggles.tex"),
	Asset("ATLAS", "images/inventoryimages/ratpoisonbottle.xml"),
	Asset("IMAGE", "images/inventoryimages/ratpoisonbottle.tex"),
	Asset("ATLAS", "images/inventoryimages/iceboomerang.xml"),
	Asset("IMAGE", "images/inventoryimages/iceboomerang.tex"),
	Asset("ATLAS", "images/inventoryimages/diseasecurebomb.xml"),
	Asset("IMAGE", "images/inventoryimages/diseasecurebomb.tex"),
	Asset("ATLAS", "images/inventoryimages/snowball_throwable.xml"),
	Asset("IMAGE", "images/inventoryimages/snowball_throwable.tex"),
	Asset("ATLAS", "images/inventoryimages/skeletonmeat.xml"),
	Asset("IMAGE", "images/inventoryimages/skeletonmeat.tex"),
	Asset("ATLAS", "images/mushroom_slot.xml"),
	Asset("IMAGE", "images/mushroom_slot.tex"),
	Asset("ATLAS", "images/inventoryimages/critterlab_real.xml"),
	Asset("IMAGE", "images/inventoryimages/critterlab_real.tex"),
	
	Asset("ANIM", "anim/geyser.zip"),
	Asset("ANIM", "anim/lava_vomit.zip"),
	Asset("ANIM", "anim/leif_root.zip"),
	Asset("ANIM", "anim/root_spike.zip"),
	Asset("ANIM", "anim/chop_root_spike.zip"),
	Asset("ANIM", "anim/snow_over.zip"),
	Asset("ANIM", "anim/sand_dune.zip"),
	Asset("ANIM", "anim/sandhill.zip"),
	Asset("ANIM", "anim/snowpile.zip"),
	Asset("ANIM", "anim/tar.zip"),
	Asset("ANIM", "anim/tar_trap.zip"),
	Asset("ANIM", "anim/swap_minotaur_boulder.zip"),
	Asset("ANIM", "anim/pillar_ruins_damaged.zip"),
	Asset("ANIM", "anim/rhino_stun.zip"),
	Asset("ANIM", "anim/charlie_fountain.zip"),
	Asset("ANIM", "anim/bush_crab.zip"),
	Asset("ANIM", "anim/creepingfear.zip"),
	Asset("ANIM", "anim/dreadeye.zip"),
	Asset("ANIM", "anim/uncompromising_shadow_projectile1_fx.zip"),
	Asset("ANIM", "anim/uncompromising_shadow_projectile2_fx.zip"),
	Asset("ANIM", "anim/hippo_attacks.zip"),
	Asset("ANIM", "anim/hippo_basic.zip"),
	Asset("ANIM", "anim/toadling.zip"),
	Asset("ANIM", "anim/iceboomerang.zip"),
	Asset("ANIM", "anim/swap_iceboomerang.zip"),
	Asset("ANIM", "anim/diseasecurebomb.zip"),
	Asset("ANIM", "anim/swap_diseasecurebomb.zip"),
	Asset("ANIM", "anim/snowball.zip"),
	Asset("ANIM", "anim/swap_snowball_throwable.zip"),
	Asset("ANIM", "anim/swap_sporepack.zip"),
	Asset("ANIM", "anim/sporepack.zip"),
	Asset("ANIM", "anim/swap_saltpack.zip"),
	Asset("ANIM", "anim/veteranshrine.zip"),
	Asset("ANIM", "anim/spider_trapdoor.zip"),
	Asset("ANIM", "anim/trapdoor.zip"),
	Asset("ANIM", "anim/plaguemask.zip"),
	Asset("ANIM", "anim/rat_tail.zip"),
	Asset("ANIM", "anim/rat_fur.zip"),
	Asset("ANIM", "anim/shroom_skin_fragment.zip"),
	Asset("ANIM", "anim/saltpack.zip"),
	Asset("ANIM", "anim/airconditioner.zip"),
	Asset("ANIM", "anim/shadow_eye.zip"),
	Asset("ANIM", "anim/honey_log.zip"),
	Asset("ANIM", "anim/bugzapper.zip"),
	Asset("ANIM", "anim/swap_bugzapper.zip"),
	Asset("ANIM", "anim/mosquito_yellow_build.zip"),
	Asset("ANIM", "anim/walrus_build_summer.zip"),
	Asset("ANIM", "anim/walrus_baby_build_summer.zip"),
	Asset("ANIM", "anim/hat_sunglasses.zip"),
	Asset("ANIM", "anim/walrus_house_summer.zip"),
	Asset("ANIM", "anim/cookiespikes.zip"),
	Asset("ANIM", "anim/gnat_cocoon.zip"),
	Asset("ANIM", "anim/slingshotammo_firecracker.zip"),
	
	Asset("ANIM", "anim/hippo_water_attacks.zip"),
	Asset("ANIM", "anim/hippo_water.zip"),

	Asset("SOUNDPACKAGE", "sound/UCSounds.fev"), 
	Asset( "SOUND", "sound/UCSounds_bank00.fsb"),

	Asset("IMAGE", "images/inventoryimages/rat_tail.tex"),
	Asset("ATLAS", "images/inventoryimages/rat_tail.xml"),
	--monster morsels from waffles, thanks
	Asset("ANIM", "anim/extra_monsterfoods.zip"),
    Asset("ANIM", "anim/extra_monsterfoods_dried.zip"),
   	Asset("IMAGE", "images/inventoryimages/cookedmonstersmallmeat.tex"),
	Asset("ATLAS", "images/inventoryimages/cookedmonstersmallmeat.xml"),
   	Asset("IMAGE", "images/inventoryimages/monstersmallmeat.tex"),
	Asset("ATLAS", "images/inventoryimages/monstersmallmeat.xml"),
   	Asset("IMAGE", "images/inventoryimages/monstersmallmeat_dried.tex"),
	Asset("ATLAS", "images/inventoryimages/monstersmallmeat_dried.xml"),
   	Asset("IMAGE", "images/inventoryimages/plaguemask.tex"),
	Asset("ATLAS", "images/inventoryimages/plaguemask.xml"),
   	Asset("IMAGE", "images/inventoryimages/shroom_skin_fragment.tex"),
	Asset("ATLAS", "images/inventoryimages/shroom_skin_fragment.xml"),
	Asset("IMAGE", "images/inventoryimages/sporepack.tex"),
	Asset("ATLAS", "images/inventoryimages/sporepack.xml"),
	Asset("IMAGE", "images/inventoryimages/saltpack.tex"),
	Asset("ATLAS", "images/inventoryimages/saltpack.xml"),
	Asset("IMAGE", "images/inventoryimages/air_conditioner.tex"),
	Asset("ATLAS", "images/inventoryimages/air_conditioner.xml"),
	Asset("IMAGE", "images/inventoryimages/honey_log.tex"),
	Asset("ATLAS", "images/inventoryimages/honey_log.xml"),
	Asset("ANIM", "anim/scorpion_basic.zip"),
	Asset("ANIM", "anim/scorpion_build.zip"),
	Asset("ANIM", "anim/scorpion_new.zip"),
	Asset("ANIM", "anim/scorpion_leave.zip"),
	Asset("ANIM", "anim/bat_vamp_build.zip"),
	Asset("ANIM", "anim/bat_vamp_shadow.zip"),
	Asset("IMAGE", "images/inventoryimages/zaspberryparfait.tex"),
	Asset("ATLAS", "images/inventoryimages/zaspberryparfait.xml"),
	Asset("IMAGE", "images/inventoryimages/bugzapper.tex"),
	Asset("ATLAS", "images/inventoryimages/bugzapper.xml"),
	Asset("IMAGE", "images/inventoryimages/sunglasses.tex"),
	Asset("ATLAS", "images/inventoryimages/sunglasses.xml"),
	Asset("IMAGE", "images/inventoryimages/slingshotammo_firecrackers.tex"),
	Asset("ATLAS", "images/inventoryimages/slingshotammo_firecrackers.xml"),
	
	Asset("ANIM", "anim/gatorsnake.zip"),
	Asset("ANIM", "anim/swilson.zip"),


	--Map Icons Start--
	Asset("IMAGE", "images/inventoryimages/seafoodpaella.tex"),
	Asset("ATLAS", "images/inventoryimages/seafoodpaella.xml"),
	Asset( "IMAGE", "images/map_icons/riceplant.tex" ),
	Asset( "ATLAS", "images/map_icons/riceplant.xml" ),
	Asset( "IMAGE", "images/map_icons/sporepack_map.tex" ),
	Asset( "ATLAS", "images/map_icons/sporepack_map.xml" ),
	Asset( "IMAGE", "images/map_icons/air_conditioner_map.tex" ),
	Asset( "ATLAS", "images/map_icons/air_conditioner_map.xml" ),
	--Map Icons End--

}
