SKINS = GLOBAL.STRINGS.SKIN_NAMES
SKINSDESC = GLOBAL.STRINGS.SKIN_DESCRIPTIONS
STRINGS = GLOBAL.STRINGS.NAMES
UI = GLOBAL.STRINGS.UI


--Re-names to existing items
STRINGS.AMULET = "Lesser Life Amulet"
STRINGS.BEESWAX = "Wax"




STRINGS.UNCOMPROMISING_RAT = "Rat"          -- Maybe change the name with a pun with Robber or Raider, any idea ?
STRINGS.UNCOMPROMISING_CAVERAT = "Cave Rat" -- The aggressive cousin
STRINGS.UNCOMPROMISING_PACKRAT = "Pack Rat" -- The hoarding cousin
STRINGS.UNCOMPROMISING_RATHERD = "Rat Burrow"
STRINGS.UNCOMPROMISING_RATBURROW = "Rat Burrow"
STRINGS.UNCOMPROMISING_WINKYBURROW = "Winky's Burrow"
STRINGS.UNCOMPROMISING_WINKYBURROW_MASTER = "Winky's Burrow"
STRINGS.UNCOMPROMISING_WINKYHOMEBURROW = "Winky's Home Burrow"
STRINGS.PIED_RAT = "Pied Piper"
STRINGS.PIED_PIPER_FLUTE = "Pied Pipers Pipe"
STRINGS.GASMASK = "Goose Mask"
STRINGS.WATER = "Rain"
STRINGS.RAIN = "Rain"
STRINGS.SPORECLOUD_TOAD = "Spore Cloud"
STRINGS.MOCK_DRAGONFLY = "Dragonfly"
STRINGS.UM_SAND = "Sand"
STRINGS.UM_SANDHILL = "Sandy Pile"
STRINGS.SNOWPILE = "Snow Pile"
STRINGS.SNOWGOGGLES = "Cats-Eye Goggles"
STRINGS.SPIDERQUEENCORPSE = "Spider Queen Corpse"
STRINGS.RATPOISON = "Poison Jam"
STRINGS.RATPOISONBOTTLE = "Poison Jam"
STRINGS.LEECHSWARM = "Leech Swarm"
STRINGS.LAITLEECH = "Lait Leech"
STRINGS.SHOCKWORM = "Depths Eel"
STRINGS.VIPERWORM = "Depths Viper"
STRINGS.VIPERLING = "Writhing Apparition"
STRINGS.VIPERLINGFRIEND = "Writhing Apparition"
STRINGS.ZASPBERRY = "Zaspberry"
STRINGS.VIPERFRUIT = "Gloomberry"
STRINGS.VIPERJAM = "Gloomberry Jam"

STRINGS.SNOWMONG = "Abominamole"
STRINGS.MINOTAUR_BOULDER = "Ancient Stone Slab"
STRINGS.MINOTAUR_BOULDER_BIG = "Giant Stone Slab"
STRINGS.MINOTAUR_ORGAN = "Organ"
STRINGS.MOCK_DRAGONFLY = "Wilting Dragonfly"

STRINGS.MOONMAW_DRAGONFLY = "Moonmaw Dragonfly"
STRINGS.MOONMAW_GLASS = "Unstable Moon Glass"
STRINGS.MOONMAW_LAVAE = "Glass Lavae"
STRINGS.MOONMAW_LAVAE_RING = STRINGS.MOONMAW_LAVAE
STRINGS.GLASS_SCALES = "Enlightened Scales"
STRINGS.MOONGLASS_GEODE = "Inert Infused Moon Chunk"
STRINGS.ARMOR_GLASSMAIL = "Shard-Scale Armor"
STRINGS.ARMOR_GLASSMAIL_SHARDS = "Moon Shard"
STRINGS.MOONMAW_TRAP = STRINGS.ALTERGUARDIAN_PHASE3TRAP

STRINGS.LAVAE2 = STRINGS.LAVAE
STRINGS.BUSHCRAB = "Bush Crab"
STRINGS.ICEBOOMERANG = "Frozen Pincer"
STRINGS.TOADLING = "Toadling"
STRINGS.UNCOMPROMISING_TOAD = "Sickly Frog"
STRINGS.DISEASECUREBOMB = "Moon Oil"
STRINGS.TOADLINGSPAWNER = "Toad Spore"
STRINGS.SNOWBALL_THROWABLE = "Snowball"
--STRINGS.NAMES.TOAD  = "Sickly Toad"
STRINGS.MONSTERSMALLMEAT = "Monster Morsel"
STRINGS.COOKEDMONSTERSMALLMEAT = "Cooked Monster Morsel"
STRINGS.MONSTERSMALLMEAT_DRIED = "Small Monster Jerky"
STRINGS.UM_MONSTEREGG = "Monster Egg"
STRINGS.UM_MONSTEREGG_COOKED = "Cooked Monster Egg"
STRINGS.VETERANSHRINE = "Melancholic Skull"

STRINGS.UM_RECORD_MENU = "Uncompromising Music"
STRINGS.UM_RECORD_WALTER = "Follow Me, Woby!"
STRINGS.UM_RECORD_WIXIE = "The Delinquent"
STRINGS.UM_RECORD_SHADOW_WIXIE = "Obscuriores Sui"
STRINGS.UM_RECORD_HOODED_WIDOW = "Arachnophobia"
STRINGS.UM_RECORD_WATHOM = "Heart Attacked!"
STRINGS.UM_RECORD_STRANGER = "A Mysterious Stranger"
STRINGS.UM_RECORD_WINKY = "Funny Little Rat"

STRINGS.RATSKIN = "Diseased Fur"

STRINGS.PLAGUEMASK = "Plague Mask"
SKINS.ms_hat_plaguemask_formal = "Faux Plague Masque"
SKINSDESC.ms_hat_plaguemask_formal = "A fancy mask to stand out in a rotting world."

SKINS.wormwood_shadow = "The Corrupted" -- personal vendetta, bruh that shit aint 'triumphant'

STRINGS.TRAPDOOR = "Inconspicuous Mound"
STRINGS.SPIDER_TRAPDOOR = "Trapdoor Spider"
STRINGS.MUTATOR_TRAPDOOR = "Trapdoor Switcherdoodle"
STRINGS.DECIDUOUS_ROOT = "Living Tree Root"
STRINGS.LAVAESLIME = "Lavae Slime"
STRINGS.SALTPACK = "Salt Shaker 3000"
STRINGS.SPOREPACK = "Spore Pack"
STRINGS.RAT_TAIL = "Rat Tail"
STRINGS.SHROOM_SKIN_FRAGMENT = "Shroom Skin Scrap"
STRINGS.AIR_CONDITIONER = "Air Conditioner" --<--
STRINGS.MINI_DREADEYE = "Shadow Eye"
STRINGS.SHADOW_GOO = "Shadow Ink"
STRINGS.UM_SCORPION = "Scorpion"
STRINGS.VAMPIREBAT = "Adult Batilisk"
STRINGS.WICKER_TENTACLE = "Sickly Tentacle"
STRINGS.SKELETONMEAT = "Long Pig"
STRINGS.ZASPBERRYPARFAIT = "Zaspberry Parfait"
STRINGS.CARAPACECOOLER = "Carapace Cooler"
STRINGS.HONEY_LOG = "Honey Log Roll"
STRINGS.RNEGHOST = "Fire Stealer"
STRINGS.CHIMP = "Random Chimp"
STRINGS.BUGZAPPER = "Bug Zapper"
STRINGS.RICE1 = "Rice Grains"
STRINGS.RICE2 = "Lice Grains"
STRINGS.RICE_COOKED1 = "Burnt Rice"
STRINGS.RICE_COOKED2 = "Burnt Lice"
STRINGS.RICEPLANT1 = "Rice"
STRINGS.RICEPLANT2 = "Lice"
STRINGS.SEAFOODPAELLA = "Seafood Paella"
STRINGS.SWILSON = "Wilson?"
STRINGS.MOTHERGOOSE1 = "Mother Goose"
STRINGS.MOTHERGOOSE2 = "Mother Moose"
STRINGS.CRITTERLAB_REAL = "Rock Den"
STRINGS.CRITTERLAB_REAL_BROKEN = "Broken Rock Den"
STRINGS.POLLENMITES = "Pollen Mites"
STRINGS.POLLENMITEDEN = "Pollen Mite Den"
STRINGS.WALRUS_CAMP_SUMMER = STRINGS.WALRUS_CAMP
STRINGS.SUNGLASSES = "Sunglasses"
STRINGS.CHARLIEPHONOGRAPH_100 = "Gramaphone"
STRINGS.STUMPLING = "Pineling"
STRINGS.BIRCHLING = "Birchling"
STRINGS.LICELOAF1 = "Liceloaf"
STRINGS.LICELOAF1 = "Riceloaf"
STRINGS.MOON_TEAR = "Moon Tear"
STRINGS.SHADOW_TELEPORTER = "Grasping Shadow"
STRINGS.WAXWELL_PACT_TRADER = "Pact Maker"
STRINGS.SCORPIONCARAPACE = "Scorpion Carapace"
STRINGS.SCORPIONCARAPACECOOKED = "Grilled Scorpion Carapace"
STRINGS.HARDSHELLTACOS = "Hard Shell Tacos"
STRINGS.SHADOW_CROWN = "Shadow Crown"
STRINGS.CALIFORNIAKING = "California King"
STRINGS.TRAPDOORGRASS = "Wide Grass"
STRINGS.LUREPLAGUE_RAT = "Lureplague Rat"
STRINGS.SNAPPERTURTLE = "Snapper Turtle"
STRINGS.SNAPPERTURTLEBABY = "Whippersnapper Turtle"
STRINGS.SNAPPERTURTLENEST = "Nest"

STRINGS.CURSED_ANTLER = "Cursed Antler"
SKINS.ms_twisted_antler = "Twisted Antler"
SKINSDESC.ms_twisted_antler = "A twisted antler for a twisted person."

STRINGS.MARSH_GRASS = "Marsh Bush"
STRINGS.GIANT_TREE = "Giant Redwood"
STRINGS.WEBBEDCREATURE = "Silky Cocoon"
STRINGS.WIDOWSGRASP = "Widow's Claw"
STRINGS.HOODEDWIDOW = "Hooded Widow"


STRINGS.WEBBEDCREATURE_BUGGY = "Buggy Cocoon"
STRINGS.WEBBEDCREATURE_GROSS = "Grotesque Cocoon"
STRINGS.WEBBEDCREATURE_HAIRY = "Hairy Cocoon"
STRINGS.WEBBEDCREATURE_HARD = "Hardened Cocoon"
STRINGS.WEBBEDCREATURE_LEATHER = "Leathery Cocoon"
STRINGS.WEBBEDCREATURE_FEATHER = "Feathery Cocoon"
STRINGS.WEBBEDCREATURE_LEAFY = "Leafy Cocoon"

STRINGS.CHOMPER = "Plant"
STRINGS.BERNIEBOX = "Cuddly Friends Toy Box"
STRINGS.SNAPDRAGON = "Snapdragon"
STRINGS.GIANT_BLUEBERRY = "Boomberry"
STRINGS.BLUEBERRYPLANT = "Boomberry Plant"
STRINGS.BLUEBERRYFLOWER = "Boomberry Flower"
STRINGS.HOODEDTRAPDOOR = "Flat Stone"
STRINGS.HOODED_FERN = "Large Fern"
STRINGS.FALLINGBEEHIVE = STRINGS.BEEHIVE
STRINGS.FRUITBAT = "Fruit Bat"
STRINGS.PITCHERPLANT = "Pitcherplant"
STRINGS.GIANT_TREE_INFESTED = "Infested Giant Redwood"
STRINGS.SNAPDRAGON_BUDDY_pale = "Pale Snap Buddy"
STRINGS.SNAPDRAGON_BUDDY_orange = "Orange Snap Buddy"
STRINGS.SNAPDRAGON_BUDDY_red = "Red Snap Buddy"
STRINGS.SNAPDRAGON_BUDDY_purple = "Purple Snap Buddy"
STRINGS.SNAPDRAGON_BUDDY_pink = "Pink Snap Buddy"
STRINGS.SNAPDRAGON_BUDDY_green = "Green Snap Buddy"
STRINGS.SNAPDRAGON_BUDDY_yellow = "Yellow Snap Buddy"
STRINGS.PALE_VOMIT = "Pale Vomit"
STRINGS.ORANGE_VOMIT = "Orange Vomit"
STRINGS.RED_VOMIT = "Red Vomit"
STRINGS.PURPLE_VOMIT = "Purple Vomit"
STRINGS.PINK_VOMIT = "Pink Vomit"
STRINGS.GREEN_VOMIT = "Green Vomit"
STRINGS.YELLOW_VOMIT = "Yellow Vomit"
STRINGS.SNAPPLANT = "Snap Plant"
STRINGS.WHISPERPOD = "Whisper Pod"
STRINGS.WHISPERPOD_NORMAL_GROUND = "Whisper Pod"
STRINGS.DEPLETED_HOODED_FERN = "Large Fern"
STRINGS.APHID = "Aphid"
STRINGS.NYMPH = "Nymph"
STRINGS.WIDOWSHEAD = "Widow's Head"
STRINGS.CCTRINKET_DON = "Torn Book"
STRINGS.CCTRINKET_JAZZY = "Rusty Saxophone"
STRINGS.CCTRINKET_FREDDO = "Broken Cassete"

STRINGS.PURPLESTEAMEDHAMS = "Steamed Hams"
STRINGS.GREENSTEAMEDHAMS = "Steamed Hams"

STRINGS.BLUEBERRYPANCAKES = "Boomberry Pancakes"
STRINGS.DEVILSFRUITCAKE = "Devils Fruit Cake"
STRINGS.SIMPSALAD = "Simple Salad"
STRINGS.BEEFALOWINGS = "Beefalo Wings"
STRINGS.PINEPILE = "Needle Pile"
STRINGS.HOODED_MUSHTREE_TALL = STRINGS.MUSHTREE_TALL
STRINGS.HOODED_MUSHTREE_MEDIUM = STRINGS.MUSHTREE_MEDIUM
STRINGS.HOODED_MUSHTREE_SMALL = STRINGS.MUSHTREE_SMALL
STRINGS.SCREECHER_TRINKET = "Lost Doll"
STRINGS.SNOWCONE = "Snowcone"
STRINGS.CINNAMON_TREE = "Cinnamon Tree"
STRINGS.CINNAMON_TREE_BURNT = "Cinnamon Tree"
STRINGS.CINNAMON_TREE_STUMP = "Cinnamon Tree"
STRINGS.WATERMELON_LANTERN = "Watermelon Lantern"
STRINGS.ANCIENT_TREPIDATION = "Trepidation"
STRINGS.ANCIENT_TREPIDATION_ARM = "Trepidation's Reach"
STRINGS.STEEL_SWEATER = "Steel Sweater"
STRINGS.RNESKELETON = "Skeleton"

STRINGS.ANCIENT_AMULET_RED = "Ancient Soul Amulet"
SKINS.ms_ancient_amulet_red_demoneye = "Demon-eyed Amulet"
SKINSDESC.ms_ancient_amulet_red = "" --TODO

STRINGS.RAT_WHIP = "Tail o' Twined Rats"
STRINGS.KLAUS_AMULET = "Naught Lock"
STRINGS.HOUND_LIGHTNING = "Supercharged Lightning"
STRINGS.LIGHTNINGHOUND = "Lightning Hound"
STRINGS.MAGMAHOUND = "Magma Hound"
STRINGS.SPOREHOUND = "Spore Hound"
STRINGS.GLACIALHOUND = "Glacial Hound"
STRINGS.CRABCLAW = "Crab Claw"
STRINGS.BIGHT = "Comingled Clockwork"
STRINGS.KNOOK = "Automaton Abomination"
STRINGS.ROSHIP = "Mechanical Monstrosity"
STRINGS.SNOTROAST = "Snot Roast"
STRINGS.LICELOAF = "Liceloaf" --For the cookbook
STRINGS.TURF_HOODEDMOSS = "Mossy Forest Turf"
STRINGS.TURF_ANCIENTHOODEDTURF = "Ancient Hooded Turf"
STRINGS.DEERCLOPS_BARRIER = "Glacial Wall"
STRINGS.PIGKING_PIGTORCH = STRINGS.PIGTORCH
STRINGS.UM_PAWN = "Clockwork Pawn"
STRINGS.UM_PAWN_NIGHTMARE = "Damaged Clockwork Pawn"
STRINGS.CAVE_ENTRANCE_SUNKDECID = STRINGS.CAVE_ENTRANCE
STRINGS.CAVE_ENTRANCE_OPEN_SUNKDECID = STRINGS.CAVE_ENTRANCE_OPEN
STRINGS.CAVE_EXIT_SUNKDECID = STRINGS.CAVE_EXIT
STRINGS.GORE_HORN_HAT = "Gore Horn"
STRINGS.SLOBBERLOBBER = "Slobber Lobber"
STRINGS.BEARGERCLAW = "Bearger Claw"
STRINGS.LAVASPIT_SLOBBER = STRINGS.LAVASPIT
STRINGS.WOODPECKER = "Woodpecker"
STRINGS.UM_BEAR_TRAP = "Snap-Trap"
STRINGS.UM_BEAR_TRAP_OLD = "Snap-Trap"
STRINGS.MOTHERMOSSLING = STRINGS.MOSSLING
STRINGS.MOTHERMOOSEEGG1 = "Golden Moose Egg"
STRINGS.MOTHERMOOSEEGG2 = "Golden Goose Egg"
STRINGS.CORNCAN = "Canned Corn"
STRINGS.SKULLCHEST_CHILD = "Skull Chest"
STRINGS.SKULLCHEST = "Skull Chest"
STRINGS.GREENFOLIAGE = "Hooded Foliage" --Well, I guess I did this then...

STRINGS.FEATHER_FROCK = "Feather Frock"
SKINS.ms_feather_frock_fancy = "Raven Cloak"
SKINSDESC.ms_feather_frock_fancy = "A fancy cloak made out of the finest feathers."

STRINGS.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "Snap-Teeth"
STRINGS.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "Shiny Snap-Teeth"
STRINGS.DRIFTWOODFISHINGROD = "Driftwood Fishing Rod"

STRINGS.REDGEM_CRACKED = "Shaped Red Gem"
STRINGS.BLUEGEM_CRACKED = "Shaped Blue Gem"
STRINGS.ORANGEGEM_CRACKED = "Shaped Orange Gem"
STRINGS.GREENGEM_CRACKED = "Shaped Green Gem"
STRINGS.YELLOWGEM_CRACKED = "Shaped Yellow Gem"
STRINGS.PURPLEGEM_CRACKED = "Shaped Purple Gem"
STRINGS.OPALPRECIOUSGEM_CRACKED = "Shaped Iridescent Gem"
STRINGS.RED_MUSHED_ROOM = "Red Mushed-Room"
STRINGS.GREEN_MUSHED_ROOM = "Green Mushed-Room"
STRINGS.BLUE_MUSHED_ROOM = "Blue Mushed-Room"

--Stanton's Stash
STRINGS.STANTON_SHADOW_TONIC = "Shadow Tonic"
STRINGS.STANTON_SHADOW_TONIC_FANCY = STRINGS.STANTON_SHADOW_TONIC
STRINGS.STANTON = "Skelton Cree"
STRINGS.SKULLFLASK = "Skull Flask"
STRINGS.SKULLFLASK_EMPTY = "Empty Skull Flask"
--Stanton's Stash

STRINGS.THEATERCORN = "Theater Corn"
STRINGS.ARMORLAVAE = "Dimvae"
STRINGS.WIDOW_WEB_COMBAT = "Sticky Webbing"

-- Blowgun stuff
STRINGS.UNCOMPROMISING_BLOWGUN = "Blowpipe" --Lol
STRINGS.BLOWGUNAMMO_TOOTH = "Dart"
STRINGS.BLOWGUNAMMO_FIRE = "Fire Dart"
STRINGS.BLOWGUNAMMO_SLEEP = "Sleep Dart"
STRINGS.BLOWGUNAMMO_ELECTRIC = "Electric Dart"

STRINGS.BOOK_RAIN_UM = "Rainy Days"

STRINGS.RAIN_HORN = "Drowning Conch"
STRINGS.FLORAL_BANDAGE = "Sweetflower Wrap"
STRINGS.DORMANT_RAIN_HORN = "Dormant Conch"

STRINGS.NIGHTCRAWLER = "Night Crawler"
STRINGS.RNE_GRABBYSHADOWS = "Grasping Fear"
STRINGS.NERVOUSTICK = "Nervous Tick"
STRINGS.NERVOUSTICKDEN = "Heart of the Swarm"
STRINGS.FUELSEEKER = "Fuel Seeker"
STRINGS.MINDWEAVER = "Mind Weaver"
STRINGS.RNEMUSHROOMBOMB = "Boomshroom"

STRINGS.HAT_BAGMASK = "Paper Bag"
STRINGS.HAT_BLACKCATMASK = "Black Cat Mask"
STRINGS.HAT_CLOWNMASK = "Clown Mask"
STRINGS.HAT_WATHOMMASK = "Creature Mask"
STRINGS.HAT_DEVILMASK = "Devil Mask"
STRINGS.HAT_FIENDMASK = "Fiend Mask"
STRINGS.HAT_GHOSTMASK = "Ghost Mask"
STRINGS.HAT_GLOBMASK = "Glob Mask"
STRINGS.HAT_HOCKEYMASK = "Hockey Mask"
STRINGS.HAT_JOYOUSMASK = "Joyous Mask"
STRINGS.HAT_MERMMASK = "Merm Mask"
STRINGS.HAT_OOZEMASK = "Ooze Mask"
STRINGS.HAT_ORANGECATMASK = "Orange Cat Mask"
STRINGS.HAT_PHANTOMMASK = "Phantom Mask"
STRINGS.HAT_PIGMASK = "Pig Mask"
STRINGS.HAT_PUMPGOREMASK = "Pumpgore Mask"
STRINGS.HAT_REDSKULLMASK = "Red Skull Mask"
STRINGS.HAT_SKULLMASK = "Skull Mask"
STRINGS.HAT_SPECTREMASK = "Spectre Mask"
STRINGS.HAT_WHITECATMASK = "White Cat Mask"
STRINGS.HAT_TECHNOMASK = "Techno-Tronic Mask"
STRINGS.HAT_MANDRAKEMASK = "Mandrake Mask"
STRINGS.HAT_OPOSSUMMASK = "Opossum Mask"
STRINGS.RNE_GOODIEBAG = "Goodie Bag"
STRINGS.HAT_RATMASK = "Rat Mask"

STRINGS.OCULET = "Oculet"
STRINGS.OCULET_REZ = "Rez"
STRINGS.OCULET_SPAZ = "Spaz"
STRINGS.WILLIAM = "William"

--Under the Weather--
STRINGS.UNCOMPROMISING_HARPOON = "Harpoon"
STRINGS.UNCOMPROMISING_HARPOON_HEAVY = "Heavy Harpoon"
STRINGS.UNCOMPROMISING_HARPOONREEL = "Reel"
STRINGS.UM_MAGNERANG = "Magnerang"
STRINGS.UM_MAGNERANGREEL = "Magnerang Magnet"
STRINGS.UNCOMPROMISING_FISHINGNET = "Fishing Net"
STRINGS.UM_BEEGUN = "Hand Held Hive"
STRINGS.UM_BEEGUN_CHERRY = "Hand Held Hibeescus Hive"
STRINGS.BULLETBEE = "Bullet Bee"
STRINGS.CHERRYBULLETBEE = "Bullet Hibeescus"
STRINGS.UM_BULLETBEE_PROJ = "Bullet Bee"
STRINGS.UM_CHERRYBULLETBEE_PROJ = "Bullet Hibeescus"

STRINGS.WINONA_TOOLBOX = "Winona's Toolbox"
STRINGS.OCEAN_SPEAKER = "Dilapidated Speaker" --Kinda lame dunno what else though.
STRINGS.OCEAN_SPEAKER_TEASER = STRINGS.OCEAN_SPEAKER
STRINGS.SUNKENCHEST_ROYAL_RANDOM = "Royal Sunken Chest"

STRINGS.SUNKENCHEST_ROYAL_RED = "Gem Encrusted Chest"
STRINGS.SUNKENCHEST_ROYAL_BLUE = STRINGS.SUNKENCHEST_ROYAL_RED
STRINGS.SUNKENCHEST_ROYAL_PURPLE = STRINGS.SUNKENCHEST_ROYAL_RED
STRINGS.SUNKENCHEST_ROYAL_GREEN = STRINGS.SUNKENCHEST_ROYAL_RED
STRINGS.SUNKENCHEST_ROYAL_ORANGE = STRINGS.SUNKENCHEST_ROYAL_RED
STRINGS.SUNKENCHEST_ROYAL_YELLOW = STRINGS.SUNKENCHEST_ROYAL_RED
STRINGS.SUNKENCHEST_ROYAL_RAINBOW = "Prismatic " .. STRINGS.SUNKENCHEST_ROYAL_RED

STRINGS.SLUDGE = "Sea Sludge"
STRINGS.SLUDGE_OIL = "Sulfur Extract"
STRINGS.BOATPATCH_SLUDGE = "Driftwood Boat Corks"
STRINGS.SLUDGESTACK = "Thermal Vent"
STRINGS.SLUDGE_SACK = "Sludge Sack"

STRINGS.ARMOR_REED_UM = "Reed Suit"
STRINGS.ARMOR_SHARKSUIT_UM = "Rock Hide Armor"

STRINGS.ROCKJAWLEATHER = "Rocky Hide"

STRINGS.LANTERN_ELECTRICAL = "Electrical Lantern"
STRINGS.MINERHAT_ELECTRICAL = "Electrical Miner Hat"

STRINGS.POWERCELL = "Energy Cell" --Single-Use Battery

STRINGS.SEAROCK_RING = "Sea Stack"
STRINGS.RR_POWERLINE = "Powerline"
STRINGS.EYEOFTERROR_MINI_ALLY = "Hardy Peeper"
STRINGS.EYEOFTERROR_MINI_GROUNDED_ALLY = "Hardy \"Egg\""
STRINGS.STUFFED_PEEPER_POPPERS = "Stuffed Peeper Poppers"
STRINGS.UM_DEVILED_EGGS = "Deviled Eggs"
STRINGS.SIREN_BIRD_NEST = "Nested Sea Stack"
STRINGS.SIREN_BIRD_NEST_TEASER = STRINGS.SIREN_BIRD_NEST
STRINGS.SIREN_THRONE = "Sirens Throne"
STRINGS.SIREN_THRONE_TEASER = STRINGS.SIREN_THRONE
STRINGS.UM_SCORPIONHOLE = "Sandy Hole"
--STRINGS.NAMES.UM_SIREN = "Siren"
STRINGS.WINONA_UPGRADEKIT_ELECTRICAL = "Electrical Conversion Kit"
STRINGS.UM_SORREL = "Sorrel"

STRINGS.CRITTER_FIGGY = "Figgy"
STRINGS.CRITTER_FIGGY_BUILDER = "Figgy"

STRINGS.PORTABLEBOAT_ITEM = "Portable Raft"
STRINGS.PORTABLEBOAT_RIPCORD = "Portable Raft Plug"

STRINGS.MASTUPGRADE_WINDTURBINE_ITEM = "Wind Turbine"

STRINGS.LUSH_ENTRANCE = "Overly Ominous Hole"
STRINGS.GIANT_TREE_BIRDNEST = "Nest"

STRINGS.CANNONBALL_SLUDGE_ITEM = "Crude Cannonball"
STRINGS.CANNONBALL_SLUDGE = "Crude Cannonball"
STRINGS.UM_COPPER_PIPE = "Copper Pipes"
STRINGS.STEERINGWHEEL_COPPER = "Copper Steering Wheel"
STRINGS.STEERINGWHEEL_COPPER_ITEM = "Copper Steering Wheel Kit"
STRINGS.BOAT_BUMPER_SLUDGE = "Sludge Bumper"
STRINGS.BOAT_BUMPER_SLUDGE_KIT = "Sludge Bumper Kit"
STRINGS.BOAT_BUMPER_COPPER = "Copper Bumper"
STRINGS.BOAT_BUMPER_COPPER_KIT = "Copper Bumper Kit"
STRINGS.HERMIT_BUNDLE_LURES = "Lure Bundle"
STRINGS.LAVASPIT_SLUDGE = "Burning Pool of Sludge"

STRINGS.KELPSTACK = "Kelpy Seastack"
STRINGS.MOSSSTACK = "Mossy Seastack"

STRINGS.SPECTER_SHIPWRECK = "Abandoned Shipwreck"
STRINGS.UM_DREAMCATCHER = "Dream Catcher"
STRINGS.UM_BRINEISHMOSS = "Brineish Moss"
STRINGS.UM_COALESCED_NIGHTMARE = "Coalesced Nightmare"
STRINGS.BRINE_BALM = "Brine Balm"
STRINGS.SLUDGE_CORK = "Sludge Plug"
STRINGS.UM_SPECTOPLASM = "Spectoplasm"
STRINGS.UM_SPECTER_AMULET = "Specter Amulet"
STRINGS.PHANTOM = "Phantom" --phantom like minecraft :-O
STRINGS.UMSS_GENERAL = "UMSS"
STRINGS.UM_DEVCAPTURE = "Devcapture Device"
STRINGS.UM_BEEGUARD_SEEKER = "Bomber Bee"
STRINGS.UM_BEEGUARD_BLOCKER = "Blocker Bee"
STRINGS.UM_BEEGUARD_SHOOTER = "Bullet Bee"

STRINGS.UM_ORNAMENT_OPOSSUM = "Opossum Decoration"
STRINGS.UM_ORNAMENT_RAT = "Rat Decoration"

STRINGS.TRINKET_WATHOM1 = "Busted Inhaler"

STRINGS.DEATHAMP = "a heart attack"

STRINGS.CODEX_MANTRA = "Codex Mantra"
STRINGS.SHADOWVORTEX = "Shadow Vortex"

-- WIXIE & WALTER RELATED STRINGS

STRINGS.WIXIE_PIANO = "Grand Piano"
STRINGS.WIXIE_PIANO_CARD = "Mysterious Paper"
STRINGS.WIXIE_CLOCK = "Grandfather Clock"
STRINGS.WIXIE_CLOCKDANGLEY1 = "Seconds Weight"
STRINGS.WIXIE_CLOCKDANGLEY2 = "Minutes Weight"
STRINGS.WIXIE_CLOCKDANGLEY3 = "Hours Weight"
STRINGS.WIXIE_WARDROBE = "Fancy Wardrobe"
STRINGS.CHARLES_T_HORSE = "Broken Toy"
STRINGS.THE_REAL_CHARLES_T_HORSE = "Charles T. Horse"
STRINGS.WOODEN_QUEEN_PIECE = "Wooden Queen"
STRINGS.WIXIE_SHADOWCLONE = "Wixie?"
STRINGS.SHADOW_WIXIE = "Wixie?"
STRINGS.WIXIE_SHADOW_CLONE = "Wixie?"
STRINGS.SHADOW_WIXIE_HELPER = "Wixie?"

STRINGS.SLINGSHOT_MATILDA = "Matilda"
STRINGS.SLINGSHOT_GNASHER = "Gnasher"

STRINGS.SLINGSHOTAMMO_LAZY = "Lazy Prankster Rounds"
STRINGS.SLINGSHOTAMMO_SHADOW = "Nightmare Rounds"
STRINGS.SLINGSHOTAMMO_FIRECRACKERS = "Firecracker Rounds"
STRINGS.SLINGSHOTAMMO_HONEY = "Honey Rounds"
STRINGS.SLINGSHOTAMMO_RUBBER = "Rubberband Rounds"
STRINGS.SLINGSHOTAMMO_TREMOR = "Tremor Rounds"
STRINGS.SLINGSHOTAMMO_MOONROCK = "Moonphase Rounds"
STRINGS.SLINGSHOTAMMO_MOONGLASS = "Moon Shard Rounds"
STRINGS.SLINGSHOTAMMO_SALT = "Salty Rounds"
STRINGS.SLINGSHOTAMMO_SLIME = "Slimey Rounds"
STRINGS.SLINGSHOTAMMO_GOOP = "Gloop Rounds"
STRINGS.SLINGSHOTAMMO_FLARE = "Flare Rounds"

STRINGS.SLINGSHOTAMMO_INSANITY = "Insanity Rounds"
STRINGS.SLINGSHOTAMMO_LUNARVINE = "Lunarvine Rounds"

STRINGS.BAGOFMARBLES = "Bag O' Marbles"

STRINGS.SLINGSHOTAMMO_LIMESTONE = "Crust Cookie Rounds"
STRINGS.SLINGSHOTAMMO_TAR = "Stick-a-Rounds"
STRINGS.SLINGSHOTAMMO_OBSIDIAN = "Obsidian Rounds"

STRINGS.PLACEHOLDER_INGREDIENT_IA_UM = "Requires Island Adventures or Uncompromising Mode!"
STRINGS.PLACEHOLDER_INGREDIENT_IA = "Requires Island Adventures!"

STRINGS.MEATRACK_HAT = "Jerky Hat"
STRINGS.FISHMEAT_DRIED = "Fish Jerky"
STRINGS.SMALLFISHMEAT_DRIED = "Small Fish Jerky"

STRINGS.WIXIEGUN =
"The Glock 17 (Beretta 92FS in the HD Edition), also known as the 9mm Pistol, is a weapon featured in Half-Life and its expansions."

STRINGS.PACT_ARMOR_SANITY = "Shadow Pact Armor"
STRINGS.PACT_SWORD_SANITY = "Shadow Pact Sword"
------------------------

STRINGS.WINONA_CATAPULT_ITEM = "Dismantled " .. STRINGS.WINONA_CATAPULT
STRINGS.WINONA_SPOTLIGHT_ITEM = "Packed " .. STRINGS.WINONA_SPOTLIGHT
STRINGS.WINONA_BATTERY_LOW_ITEM = "Dissasembled " .. STRINGS.WINONA_BATTERY_LOW
STRINGS.WINONA_BATTERY_HIGH_ITEM = STRINGS.WINONA_BATTERY_HIGH .. " Parts"

STRINGS.STAFF_STARFALL = "Starfall Staff"
STRINGS.STAFF_MOONFALL = "Moonfall Staff"
STRINGS.HAT_CRAB = "Crab Crown"
STRINGS.HAT_CRAB_ICE = "Frigid Crown"
STRINGS.KALEIDOSCOPE = "Kaleidoscope"
STRINGS.ARMOR_CRAB_MAXHP = "Gem Encrusted Shell Armor"
STRINGS.ARMOR_CRAB_REGEN = "Healing Rock Armor"
STRINGS.MOON_BEACON_KIT = "Inactive Moon Beacon"
STRINGS.MOON_BEACON = "Moon Beacon"

STRINGS.MARA_BOSS1 = "Sans Undertale From The Hit Series Super Smash Brothers (Featuring Minecraft Steve) [& Knuckles]"
STRINGS.MARA_BOSS1_BULLETS = "a bad time"

-- Pyre Nettle stuff
STRINGS.UM_PYRE_NETTLES = "Pyre Nettles"
STRINGS.UM_SMOLDER_SPORE = "Smolder Spore"
STRINGS.UM_ARMOR_PYRE_NETTLES = "Pyre Mantle"
STRINGS.UM_BLOWDART_PYRE = "Pyre Dart"

-- Mutation Extrapolation
STRINGS.UMDEBUFF_MOONBURN = "a moonburn"
STRINGS.UMDEBUFF_MOONBURN_TESTINGSTICK = "Magic Pain Stick"

-- Under the Weather Part 1
STRINGS.ALPHA_LIGHTNINGGOAT = "Alpha Volt Goat"
STRINGS.UM_TORNADO = "Giant Tornado"
STRINGS.UM_WATERFALL = "Waterfall"
STRINGS.PORTABLEBOAT = "Portable Raft"

STRINGS.UM_WINDTURBINE = "Wind Turbine"
STRINGS.MASTUPGRADE_WINDTURBINE = "Wind Turbine"

STRINGS.PIGKING_PIGGUARD = STRINGS.PIGGUARD
