
STRINGS = GLOBAL.STRINGS.NAMES
	
	STRINGS.UNCOMPROMISING_RAT = "Rat" -- Maybe change the name with a pun with Robber or Raider, any idea ?
	STRINGS.UNCOMPROMISING_RATHOLD = "Burrow"
	STRINGS.GASMASK = "Gas Mask"
	STRINGS.WATER = "Rain"
	STRINGS.RAIN = "Rain"
	STRINGS.SPORECLOUD_TOAD = "Spore Cloud"
	STRINGS.MOCK_DRAGONFLY = STRINGS.DRAGONFLY
	STRINGS.SPIDERQUEENCORPSE = "Spider Queen"