Assets = {
    -- Livingtree root attack custom art by @Advent (modded from poison birchnut roots)
    Asset("ANIM", "anim/tree_leaf_spike_lt.zip"),
    Asset("ANIM", "anim/frog_yellow_build.zip"),
	Asset("ANIM", "anim/acid_meter.zip"),
	Asset("ANIM", "anim/deerclops_ground_fx.zip"),
	Asset("ANIM", "anim/deerclopsfalling.zip"),
	Asset("ANIM", "anim/player_sneeze.zip"),
	Asset("ANIM", "anim/hat_gasmask.zip"),
	Asset("ANIM", "anim/hat_snowgoggles.zip"),
	
	Asset("ATLAS", "images/fx4.xml"),
	Asset("IMAGE", "images/fx4.tex"),
	Asset("ATLAS", "images/inventoryimages/gasmask.xml"),
	Asset("IMAGE", "images/inventoryimages/gasmask.tex"),
	Asset("ATLAS", "images/inventoryimages/sand.xml"),
	Asset("IMAGE", "images/inventoryimages/sand.tex"),
	Asset("ATLAS", "images/inventoryimages/snowgoggles.xml"),
	Asset("IMAGE", "images/inventoryimages/snowgoggles.tex"),
	Asset("ATLAS", "images/inventoryimages/ratpoisonbottle.xml"),
	Asset("IMAGE", "images/inventoryimages/ratpoisonbottle.tex"),
	Asset("ATLAS", "images/inventoryimages/cookedmonstermorsel.xml"),
	Asset("IMAGE", "images/inventoryimages/cookedmonstermorsel.tex"),
	Asset("ATLAS", "images/inventoryimages/monstermorsel.xml"),
	Asset("IMAGE", "images/inventoryimages/monstermorsel.tex"),
	
	Asset("ANIM", "anim/geyser.zip"),
	Asset("ANIM", "anim/lava_vomit.zip"),
	Asset("ANIM", "anim/leif_root.zip"),
	Asset("ANIM", "anim/root_spike.zip"),
	Asset("ANIM", "anim/chop_root_spike.zip"),
	Asset("ANIM", "anim/snow_over.zip"),
	Asset("ANIM", "anim/sand_dune.zip"),
	Asset("ANIM", "anim/sandhill.zip"),
	Asset("ANIM", "anim/snowpile.zip"),
	Asset("ANIM", "anim/tar.zip"),
	Asset("ANIM", "anim/tar_trap.zip"),
	Asset("ANIM", "anim/swap_minotaur_boulder.zip"),
	Asset("ANIM", "anim/pillar_ruins_damaged.zip"),
	Asset("ANIM", "anim/monstermorsel.zip"),
	Asset("ANIM", "anim/rhino_stun.zip"),
	Asset("ANIM", "anim/charlie_fountain.zip"),
	Asset("ANIM", "anim/bush_crab.zip"),
	Asset("ANIM", "anim/creepingfear.zip"),
	Asset("ANIM", "anim/dreadeye.zip"),
	Asset("ANIM", "anim/uncompromising_shadow_projectile1_fx.zip"),
	Asset("ANIM", "anim/uncompromising_shadow_projectile2_fx.zip"),
	
	Asset("SOUNDPACKAGE", "sound/dontstarve_DLC003.fev"), 
	Asset( "SOUND", "sound/DLC003_sfx.fsb"), 
}
