Assets = {
	----Turf
	Asset( "IMAGE", "levels/textures/noise_jungle.tex" ),
	Asset( "IMAGE", "levels/textures/mini_noise_jungle.tex" ),
	Asset( "IMAGE", "levels/tiles/jungle.tex" ),
	Asset( "FILE", "levels/tiles/jungle.xml" ),
	Asset("ANIM", "anim/swturf.zip"),
	Asset("ATLAS", "images/inventoryimages/turf_jungle.xml"),
	Asset("IMAGE", "images/inventoryimages/turf_jungle.tex"),
	----Turf


    -- Livingtree root attack custom art by @Advent (modded from poison birchnut roots)
    Asset("ANIM", "anim/tree_leaf_spike_lt.zip"),
    Asset("ANIM", "anim/frog_yellow_build.zip"),
	Asset("ANIM", "anim/acid_meter.zip"),
	Asset("ANIM", "anim/deerclops_ground_fx.zip"),
	Asset("ANIM", "anim/deerclopsfalling.zip"),
	Asset("ANIM", "anim/player_sneeze.zip"),
	Asset("ANIM", "anim/hat_gasmask.zip"),
	Asset("ANIM", "anim/hat_snowgoggles.zip"),
	
	Asset("ATLAS", "images/fx4.xml"),
	Asset("IMAGE", "images/fx4.tex"),
	Asset("ATLAS", "images/fx5.xml"),
	Asset("IMAGE", "images/fx5.tex"),
	Asset("ATLAS", "images/californiakingoverlay.xml"),
	Asset("IMAGE", "images/californiakingoverlay.tex"),
	Asset("ATLAS", "images/hoodedcanopyoverlay.xml"),
	Asset("IMAGE", "images/hoodedcanopyoverlay.tex"),
	Asset("ATLAS", "images/inventoryimages/gasmask.xml"),
	Asset("IMAGE", "images/inventoryimages/gasmask.tex"),
	Asset("ATLAS", "images/inventoryimages/sand.xml"),
	Asset("IMAGE", "images/inventoryimages/sand.tex"),
	Asset("ATLAS", "images/inventoryimages/snowgoggles.xml"),
	Asset("IMAGE", "images/inventoryimages/snowgoggles.tex"),
	Asset("ATLAS", "images/inventoryimages/ratpoisonbottle.xml"),
	Asset("IMAGE", "images/inventoryimages/ratpoisonbottle.tex"),
	Asset("ATLAS", "images/inventoryimages/iceboomerang.xml"),
	Asset("IMAGE", "images/inventoryimages/iceboomerang.tex"),
	Asset("ATLAS", "images/inventoryimages/diseasecurebomb.xml"),
	Asset("IMAGE", "images/inventoryimages/diseasecurebomb.tex"),
	Asset("ATLAS", "images/inventoryimages/snowball_throwable.xml"),
	Asset("IMAGE", "images/inventoryimages/snowball_throwable.tex"),
	Asset("ATLAS", "images/inventoryimages/skeletonmeat.xml"),
	Asset("IMAGE", "images/inventoryimages/skeletonmeat.tex"),
	Asset("ATLAS", "images/mushroom_slot.xml"),
	Asset("IMAGE", "images/mushroom_slot.tex"),
	Asset("ATLAS", "images/inventoryimages/critterlab_real.xml"),
	Asset("IMAGE", "images/inventoryimages/critterlab_real.tex"),
	Asset("ATLAS", "images/inventoryimages/bloomershot.xml"),
	Asset("IMAGE", "images/inventoryimages/bloomershot.tex"),
	
	Asset("ANIM", "anim/geyser.zip"),
	Asset("ANIM", "anim/lava_vomit.zip"),
	Asset("ANIM", "anim/leif_root.zip"),
	Asset("ANIM", "anim/root_spike.zip"),
	Asset("ANIM", "anim/chop_root_spike.zip"),
	Asset("ANIM", "anim/snow_over.zip"),
	Asset("ANIM", "anim/sand_dune.zip"),
	Asset("ANIM", "anim/sandhill.zip"),
	Asset("ANIM", "anim/snowpile.zip"),
	Asset("ANIM", "anim/tar.zip"),
	Asset("ANIM", "anim/tar_trap.zip"),
	Asset("ANIM", "anim/swap_minotaur_boulder.zip"),
	Asset("ANIM", "anim/pillar_ruins_damaged.zip"),
	Asset("ANIM", "anim/rhino_stun.zip"),
	Asset("ANIM", "anim/bush_crab.zip"),
	Asset("ANIM", "anim/creepingfear.zip"),
	Asset("ANIM", "anim/dreadeye.zip"),
	Asset("ANIM", "anim/uncompromising_shadow_projectile1_fx.zip"),
	Asset("ANIM", "anim/uncompromising_shadow_projectile2_fx.zip"),
	Asset("ANIM", "anim/hippo_attacks.zip"),
	Asset("ANIM", "anim/hippo_basic.zip"),
	Asset("ANIM", "anim/toadling.zip"),
	Asset("ANIM", "anim/iceboomerang.zip"),
	Asset("ANIM", "anim/swap_iceboomerang.zip"),
	Asset("ANIM", "anim/diseasecurebomb.zip"),
	Asset("ANIM", "anim/swap_diseasecurebomb.zip"),
	Asset("ANIM", "anim/snowball.zip"),
	Asset("ANIM", "anim/swap_snowball_throwable.zip"),
	Asset("ANIM", "anim/swap_sporepack.zip"),
	Asset("ANIM", "anim/sporepack.zip"),
	Asset("ANIM", "anim/swap_saltpack.zip"),
	Asset("ANIM", "anim/veteranshrine.zip"),
	Asset("ANIM", "anim/spider_trapdoor.zip"),
	Asset("ANIM", "anim/trapdoor.zip"),
	Asset("ANIM", "anim/rock_flipping.zip"),
	Asset("ANIM", "anim/plaguemask.zip"),
	Asset("ANIM", "anim/rat_tail.zip"),
	Asset("ANIM", "anim/rat_fur.zip"),
	Asset("ANIM", "anim/shroom_skin_fragment.zip"),
	Asset("ANIM", "anim/saltpack.zip"),
	Asset("ANIM", "anim/airconditioner.zip"),
	Asset("ANIM", "anim/shadow_eye.zip"),
	Asset("ANIM", "anim/honey_log.zip"),
	Asset("ANIM", "anim/bugzapper.zip"),
	Asset("ANIM", "anim/swap_bugzapper.zip"),
	Asset("ANIM", "anim/mosquito_yellow_build.zip"),
	Asset("ANIM", "anim/walrus_build_summer.zip"),
	Asset("ANIM", "anim/walrus_baby_build_summer.zip"),
	Asset("ANIM", "anim/hat_sunglasses.zip"),
	Asset("ANIM", "anim/walrus_house_summer.zip"),
	Asset("ANIM", "anim/cookiespikes.zip"),
	Asset("ANIM", "anim/gnat_cocoon.zip"),
	Asset("ANIM", "anim/slingshotammo_firecracker.zip"),
	Asset("ANIM", "anim/phonograph.zip"),
	Asset("ANIM", "anim/moontear.zip"),
	Asset("ANIM", "anim/shadow_teleporter.zip"),
	Asset("ANIM", "anim/hat_shadowcrown.zip"),
	Asset("ANIM", "anim/critterlab_broken.zip"),
	Asset("ANIM", "anim/swap_nightstick_off.zip"),
	Asset("ANIM", "anim/bloomershot.zip"),
	Asset("ANIM", "anim/snapdragon.zip"),
	Asset("ANIM", "anim/snapdragon_build.zip"),
	Asset("ANIM", "anim/snapdragon_build_seeds.zip"),
	Asset("ANIM", "anim/snapdragon_build_dragonfruit_seeds.zip"),
	Asset("ANIM", "anim/snapdragon_build_durian_seeds.zip"),
	Asset("ANIM", "anim/snapdragon_build_eggplant_seeds.zip"),
	Asset("ANIM", "anim/snapdragon_build_pomegranate_seeds.zip"),
	Asset("ANIM", "anim/snapdragon_build_pumpkin_seeds.zip"),
	Asset("ANIM", "anim/snapdragon_build_watermelon_seeds.zip"),
	Asset("ANIM", "anim/snapdragon_build_neck.zip"),
	Asset("ANIM", "anim/snapdragon_build_frozen.zip"),
	Asset("ANIM", "anim/whisperpod.zip"),
	Asset("ANIM", "anim/whisperpod_normal_ground.zip"),
	Asset("ANIM", "anim/hound_lightning.zip"),
	
	Asset("ANIM", "anim/hippo_water_attacks.zip"),
	Asset("ANIM", "anim/hippo_water.zip"),

	Asset("SOUNDPACKAGE", "sound/UCSounds.fev"), 
	Asset( "SOUND", "sound/UCSounds_bank00.fsb"),

	Asset("IMAGE", "images/inventoryimages/rat_tail.tex"),
	Asset("ATLAS", "images/inventoryimages/rat_tail.xml"),
	--monster morsels from waffles, thanks
	Asset("ANIM", "anim/extra_monsterfoods.zip"),
    Asset("ANIM", "anim/extra_monsterfoods_dried.zip"),
   	Asset("IMAGE", "images/inventoryimages/cookedmonstersmallmeat.tex"),
	Asset("ATLAS", "images/inventoryimages/cookedmonstersmallmeat.xml"),
   	Asset("IMAGE", "images/inventoryimages/monstersmallmeat.tex"),
	Asset("ATLAS", "images/inventoryimages/monstersmallmeat.xml"),
   	Asset("IMAGE", "images/inventoryimages/monstersmallmeat_dried.tex"),
	Asset("ATLAS", "images/inventoryimages/monstersmallmeat_dried.xml"),
   	Asset("IMAGE", "images/inventoryimages/plaguemask.tex"),
	Asset("ATLAS", "images/inventoryimages/plaguemask.xml"),
   	Asset("IMAGE", "images/inventoryimages/shroom_skin_fragment.tex"),
	Asset("ATLAS", "images/inventoryimages/shroom_skin_fragment.xml"),
	Asset("IMAGE", "images/inventoryimages/sporepack.tex"),
	Asset("ATLAS", "images/inventoryimages/sporepack.xml"),
	Asset("IMAGE", "images/inventoryimages/saltpack.tex"),
	Asset("ATLAS", "images/inventoryimages/saltpack.xml"),
	Asset("IMAGE", "images/inventoryimages/air_conditioner.tex"),
	Asset("ATLAS", "images/inventoryimages/air_conditioner.xml"),
	Asset("IMAGE", "images/inventoryimages/honey_log.tex"),
	Asset("ATLAS", "images/inventoryimages/honey_log.xml"),
	Asset("IMAGE", "images/inventoryimages/aphid.tex"),
	Asset("ATLAS", "images/inventoryimages/aphid.xml"),
	
	Asset("ANIM", "anim/scorpion_basic.zip"),
	Asset("ANIM", "anim/scorpion_build.zip"),
	Asset("ANIM", "anim/scorpion_new.zip"),
	Asset("ANIM", "anim/scorpion_leave.zip"),
	Asset("ANIM", "anim/bat_vamp_build.zip"),
	Asset("ANIM", "anim/bat_vamp_shadow.zip"),
	Asset("ANIM", "anim/berniebox.zip"),
	
	Asset("IMAGE", "images/inventoryimages/zaspberryparfait.tex"),
	Asset("ATLAS", "images/inventoryimages/zaspberryparfait.xml"),
	Asset("IMAGE", "images/inventoryimages/bugzapper.tex"),
	Asset("ATLAS", "images/inventoryimages/bugzapper.xml"),
	Asset("IMAGE", "images/inventoryimages/sunglasses.tex"),
	Asset("ATLAS", "images/inventoryimages/sunglasses.xml"),
	Asset("IMAGE", "images/inventoryimages/slingshotammo_firecrackers.tex"),
	Asset("ATLAS", "images/inventoryimages/slingshotammo_firecrackers.xml"),
	Asset("IMAGE", "images/inventoryimages/moon_tear.tex"),
	Asset("ATLAS", "images/inventoryimages/moon_tear.xml"),
	Asset("IMAGE", "images/inventoryimages/shadow_crown.tex"),
	Asset("ATLAS", "images/inventoryimages/shadow_crown.xml"),
	Asset("IMAGE", "images/inventoryimages/berniebox.tex"),
	Asset("ATLAS", "images/inventoryimages/berniebox.xml"),
	Asset("IMAGE", "images/inventoryimages/whisperpod.tex"),
	Asset("ATLAS", "images/inventoryimages/whisperpod.xml"),
	
	--Asset("ANIM", "anim/gatorsnake.zip"),
	Asset("ANIM", "anim/swilson.zip"),
	Asset("ANIM", "anim/stumpling.zip"),
	Asset("IMAGE", "images/vetskull.tex"),
	Asset("ATLAS", "images/vetskull.xml"),
	--Asset("IMAGE", "images/inventoryimages/liceloaf.tex"),
	--Asset("ATLAS", "images/inventoryimages/liceloaf.xml"),
	--Asset("ANIM", "anim/liceloaf.zip"),
	Asset("IMAGE", "images/inventoryimages/scorpioncarapace.tex"),
	Asset("ATLAS", "images/inventoryimages/scorpioncarapace.xml"),
	Asset("IMAGE", "images/inventoryimages/scorpioncarapacecooked.tex"),
	Asset("ATLAS", "images/inventoryimages/scorpioncarapacecooked.xml"),
	Asset("ANIM", "anim/scorpioncarapace.zip"),
	Asset("ANIM", "anim/scorpioncarapace_dried.zip"),
	Asset("IMAGE", "images/inventoryimages/hardshelltacos.tex"),
	Asset("ATLAS", "images/inventoryimages/hardshelltacos.xml"),
	Asset("ANIM", "anim/hardshelltacos.zip"),
	Asset("IMAGE", "images/inventoryimages/californiaking.tex"),
	Asset("ATLAS", "images/inventoryimages/californiaking.xml"),
	Asset("ANIM", "anim/californiaking.zip"),
	Asset("ANIM", "anim/trapdoorgrass.zip"),
	Asset("ANIM", "anim/lureplague_rat.zip"),
	Asset("ANIM", "anim/snapperturtle.zip"),
	Asset("ANIM", "anim/snapperturtle_water.zip"),
	Asset("ANIM", "anim/beefalo_paw.zip"),
	Asset("ANIM", "anim/bush_marsh.zip"),
    Asset("ANIM", "anim/cursed_antler.zip"),
    Asset("ANIM", "anim/swap_cursed_antler.zip"),
	Asset("IMAGE", "images/inventoryimages/cursed_antler.tex"),
	Asset("ATLAS", "images/inventoryimages/cursed_antler.xml"),
	Asset("ANIM", "anim/web_net_splat.zip"),
	Asset("ANIM", "anim/web_net_splash.zip"),
	Asset("ANIM", "anim/web_net_shot.zip"),
	Asset("ANIM", "anim/web_net_trap.zip"),
	Asset("ANIM", "anim/hoodedcanopy.zip"),
	Asset("ANIM", "anim/chomper.zip"),
	Asset("ANIM", "anim/widow.zip"),
	Asset("ANIM", "anim/blueberryplant.zip"),
	Asset("IMAGE", "images/inventoryimages/seafoodpaella.tex"),
	Asset("ATLAS", "images/inventoryimages/seafoodpaella.xml"),
	Asset("IMAGE", "images/inventoryimages/giant_blueberry.tex"),
	Asset("ATLAS", "images/inventoryimages/giant_blueberry.xml"),
	Asset("ANIM", "anim/blueberry.zip"),
	Asset("ANIM", "anim/sheeplet.zip"),
	Asset("ANIM", "anim/sheepletbomb.zip"),
	Asset("ANIM", "anim/hooded_ferns.zip"),
	Asset("ANIM", "anim/aphid.zip"), 
	Asset("ANIM", "anim/weevole.zip"),
	Asset("ANIM", "anim/widowsgrasp.zip"), 
	Asset("ANIM", "anim/swap_widowsgrasp.zip"),
	Asset("ANIM", "anim/fruitbat.zip"),
	Asset("ANIM", "anim/pitcher.zip"),
	Asset("IMAGE", "images/inventoryimages/widowsgrasp.tex"),
	Asset("ATLAS", "images/inventoryimages/widowsgrasp.xml"),
	Asset("ANIM", "anim/giant_tree_infested.zip"),
	Asset("ANIM", "anim/largefern.zip"),
	Asset("ANIM", "anim/hat_widowshead.zip"),
	Asset("IMAGE", "images/inventoryimages/widowshead.tex"),
	Asset("ATLAS", "images/inventoryimages/widowshead.xml"),
	--Map Icons Start--
	Asset( "IMAGE", "images/map_icons/riceplant.tex" ),
	Asset( "ATLAS", "images/map_icons/riceplant.xml" ),
	Asset( "IMAGE", "images/map_icons/sporepack_map.tex" ),
	Asset( "ATLAS", "images/map_icons/sporepack_map.xml" ),
	Asset( "IMAGE", "images/map_icons/air_conditioner_map.tex" ),
	Asset( "ATLAS", "images/map_icons/air_conditioner_map.xml" ),
	Asset( "IMAGE", "images/map_icons/blueberryplant_map.tex" ),
	Asset( "ATLAS", "images/map_icons/blueberryplant_map.xml" ),
	Asset( "IMAGE", "images/map_icons/giant_tree.tex" ),
	Asset( "ATLAS", "images/map_icons/giant_tree.xml" ),
	Asset( "IMAGE", "images/map_icons/pitcher.tex" ),
	Asset( "ATLAS", "images/map_icons/pitcher.xml" ),
	--Map Icons End--

	Asset( "IMAGE", "bigportraits/willow.tex" ),
    Asset( "ATLAS", "bigportraits/willow.xml" ),
	Asset( "IMAGE", "bigportraits/willow_none.tex" ),
    Asset( "ATLAS", "bigportraits/willow_none.xml" ),

}
