AddMinimapAtlas("images/map_icons/riceplant.xml")
AddMinimapAtlas("images/map_icons/sporepack_map.xml")
AddMinimapAtlas("images/map_icons/air_conditioner_map.xml")
AddMinimapAtlas("images/map_icons/giant_tree.xml")
AddMinimapAtlas("images/map_icons/pitcher.xml")