
ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WARLY
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WARLY.DESCRIBE

--	[ 		Warly Descriptions		]	--

GLOBAL.STRINGS.CHARACTERS.WARLY.ANNOUNCE_WINONAGEN = "I am a cook, not an engineer"