
ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WATHGRITHR
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE

--	[ 		Wigfrid Descriptions		]	--

GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_WINONAGEN = "What is this fancy machinery? I don't need it."