
ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE

--	[ 		Wickerbottom Descriptions		]	--

GLOBAL.STRINGS.CHARACTERS.WENDY.ANNOUNCE_WINONAGEN = "Wish I could have a manual I can read for this model"