
ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WILLOW
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE

--	[ 		Willow Descriptions		]	--

GLOBAL.STRINGS.CHARACTERS.WILLOW.ANNOUNCE_WINONAGEN = "Don't make me burn you"