
ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WOLFGANG
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE

--	[ 		Wolfgang Descriptions		]	--

GLOBAL.STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_WINONAGEN = "Is complicated, I do not get."