
ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WOODIE
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE

--	[ 			Woodie Descriptions			]	--

GLOBAL.STRINGS.CHARACTERS.WOODIE.ANNOUNCE_WINONAGEN = "No use wasting time on this thing"