ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WORMWOOD
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WORMWOOD.DESCRIBE

--	[ 		Wormwood Descriptions		]	--

    ANNOUNCE.ANNOUNCE_HARDCORE_RES = "Goes in meat parts"
    ANNOUNCE.ANNOUNCE_WINONAGEN = "How do make go?"
    ANNOUNCE.ANNOUNCE_RATRAID = "Squeak!"
    ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "Stealer squeak sqeaks!"
    ANNOUNCE.ANNOUNCE_RATRAID_OVER = "Squeaky go home?"
    ANNOUNCE.ANNOUNCE_ACIDRAIN = {
        "Water hurt?!",
        "Water burn!",
        "Why water bad?!",
    }
    ANNOUNCE.ANNOUNCE_TOADSTOOLED = "Friends? Sick friends! No! Bad!"
	--FoodBuffs
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "ssSsooo cCccold"
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "feel like twig"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "Feeling better now"
	--FoodBuffs
	
	--CaliforniaKing
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "What"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "Huh"
	DESCRIBE.CALIFORNIAKING = "Smelly drink"
	--CaliforniaKing
	
	ANNOUNCE.ANNOUNCE_RNEFOG = "Being watched"
    DESCRIBE.UNCOMPROMISING_RAT = "Hairy stuff stealer"
    DESCRIBE.UNCOMPROMISING_RATHOLD = "Squeaker hole"
    DESCRIBE.RATPOISONBOTTLE = "Friend hat soup!"
    DESCRIBE.RATPOISON = "Smell good"

    DESCRIBE.MONSTERSMALLMEAT = "Not angry now"
    DESCRIBE.COOKEDMONSTERSMALLMEAT = "Weird belly stuff"
    DESCRIBE.MONSTERSMALLMEAT_DRIED = "Chewy!"

    DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "Friend, please stop"
    DESCRIBE.TOADLING = "Friend ribbit?"
	
    DESCRIBE.GASMASK = "Breather with Tweeter clothes"
	DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
	DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
	DESCRIBE.SPIDERQUEENCORPSE = "Sleeping?"
	ANNOUNCE.ANNOUNCE_SNEEZE = "Hiccup!"
	ANNOUNCE.ANNOUNCE_HAYFEVER = "Happy time is coming!"
	ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "Oh. Happy time gone"
	ANNOUNCE.ANNOUNCE_FIREFALL = {
		"Scary!",
		"Fire! Hurt friends!",
		"Not friend! Not friend!!!",
	}
	ANNOUNCE.ANNOUNCE_ROOTING = "Bad hug!"
	ANNOUNCE.SHADOWTALKER = {
        "ALONE",
        "NOT LIKE THEM",
        "SAD",
    }
	DESCRIBE.SAND = "Dirt"
	DESCRIBE.SANDHILL = "Pile of dirt"
	DESCRIBE.SNOWPILE = "Friend killer!"
	DESCRIBE.SNOWGOGGLES = "Kitty eyes?"
	
	DESCRIBE.SNOWMONG = "Cold Digger!"
	DESCRIBE.SHOCKWORM = "Zzzzt Wiggler!"
	DESCRIBE.ZASPBERRY = "Zzzzt Food"
	DESCRIBE.ICEBOOMERANG = "Make things stop"
	DESCRIBE.VETERANSHRINE = "Sad head?"
	DESCRIBE.SNOWBALL_THROWABLE = "Fun?"
	DESCRIBE.RAT_TAIL = "Small black butt"
	DESCRIBE.PLAGUEMASK = "Bird face"
	DESCRIBE.SPIDER_TRAPDOOR = "No hair on leggy bug?"
	DESCRIBE.TRAPDOOR = "More friend hair."
	DESCRIBE.WICKER_TENTACLE = "Wigglers sick?"
	DESCRIBE.HONEY_LOG = "Me, becomes me."

	DESCRIBE.BUSHCRAB = "Friend? Yes... no?"
	DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
	DESCRIBE.DISEASECUREBOMB = "Cure friends!"
	DESCRIBE.SHROOM_SKIN_FRAGMENT = "Can't chew"
	DESCRIBE.AIR_CONDITIONER = "No more happy time?"
	DESCRIBE.SPOREPACK = "What wrong?"
	DESCRIBE.SALTPACK = "Taste funny"
	
	DESCRIBE.SCORPION = "Stabby bzzter"
	DESCRIBE.SCORPIONCARAPACE = "Is crunchy bzzter"
	DESCRIBE.SCORPIONCARAPACECOOKED = "Burnt bzzter"
	DESCRIBE.HARDSHELLTACOS = "Remembering Home"
	
	DESCRIBE.SKELETONMEAT = "Mmmm, chewy"
	DESCRIBE.CHIMP = DESCRIBE.MONKEY
	DESCRIBE.SWILSON = "Friend?.. No."
	DESCRIBE.VAMPIREBAT = "Flying claws"
								
	--Swampyness
	DESCRIBE.RICEPLANT = "Water friend!"
	DESCRIBE.RICE = "Water friend babies."
	DESCRIBE.RICE_COOKED = "Sniff."
	DESCRIBE.SEAFOODPAELLA = "Sniff Sniff."
	DESCRIBE.LICELOAF = "Lots of water friend babies."
	DESCRIBE.SUNGLASSES = "Fire ball blockers."
	
	DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
	DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.FIRECRACKERS
	DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
	DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
	DESCRIBE.BUGZAPPER = "Bzzter Basher"
	DESCRIBE.STUMPLING = "Small friend not happy."
	DESCRIBE.MOON_TEAR = "Home sick..."
	DESCRIBE.SHADOW_TELEPORTER = "Greedy grabber."
	DESCRIBE.POLLENMITEDEN = "Hello?"
    DESCRIBE.POLLENMITES = "Stay away, Bzzters!"
    DESCRIBE.SHADOW_CROWN = "Hurts more, but go faster?"
    DESCRIBE.RNEGHOST = DESCRIBE.GHOST