ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WORMWOOD
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WORMWOOD.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WORMWOOD.ACTIONFAIL

--	[ 		Wormwood Descriptions		]	--

    ANNOUNCE.ANNOUNCE_HARDCORE_RES = "Goes in meat parts"
    ANNOUNCE.ANNOUNCE_WINONAGEN = "How do make go?"
    ANNOUNCE.ANNOUNCE_RATRAID = "Squeak!"
    ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "Stealer squeak sqeaks!"
    ANNOUNCE.ANNOUNCE_RATRAID_OVER = "Squeaky go home?"
    ANNOUNCE.ANNOUNCE_ACIDRAIN = {
        "Water hurt?!",
        "Water burn!",
        "Why water bad?!",
    }
    ANNOUNCE.ANNOUNCE_TOADSTOOLED = "Friends? Sick friends! No! Bad!"
	--FoodBuffs
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "ssSsooo cCccold"
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "feel like twig"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "Feeling better now"
	--FoodBuffs
	
	--CaliforniaKing
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "What"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "Huh"
	DESCRIBE.CALIFORNIAKING = "Smelly drink"
	--CaliforniaKing
	
	ANNOUNCE.ANNOUNCE_RNEFOG = "Being watched"
    DESCRIBE.UNCOMPROMISING_RAT = "Hairy stuff stealer"
    DESCRIBE.UNCOMPROMISING_RATHOLD = "Squeaker hole"
    DESCRIBE.RATPOISONBOTTLE = "Friend hat soup!"
    DESCRIBE.RATPOISON = "Smell good"

    DESCRIBE.MONSTERSMALLMEAT = "Not angry now"
    DESCRIBE.COOKEDMONSTERSMALLMEAT = "Weird belly stuff"
    DESCRIBE.MONSTERSMALLMEAT_DRIED = "Chewy!"

    DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "Friend, please stop"
    DESCRIBE.TOADLING = "Friend ribbit?"
	
    DESCRIBE.GASMASK = "Breather with Tweeter clothes"
	DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
	DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
	DESCRIBE.SPIDERQUEENCORPSE = "Sleeping?"
	ANNOUNCE.ANNOUNCE_SNEEZE = "Hiccup!"
	ANNOUNCE.ANNOUNCE_HAYFEVER = "Happy time is coming!"
	ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "Oh. Happy time gone"
	ANNOUNCE.ANNOUNCE_FIREFALL = {
		"Scary!",
		"Fire! Hurt friends!",
		"Not friend! Not friend!!!",
	}
	ANNOUNCE.ANNOUNCE_ROOTING = "Bad hug!"
	ANNOUNCE.ANNOUNCE_SNOWSTORM = "Wind chilly. Snow coming."
	ANNOUNCE.SHADOWTALKER = {
        "ALONE",
        "NOT LIKE THEM",
        "SAD",
    }
	ANNOUNCE.ANNOUNCE_OVER_EAT =
	{
		STUFFED = "Too much belly stuff",
		OVERSTUFFED = "Too full!",
    }
	DESCRIBE.SAND = "Dirt"
	DESCRIBE.SANDHILL = "Pile of dirt"
	DESCRIBE.SNOWPILE = "Friend killer!"
	DESCRIBE.SNOWGOGGLES = "Kitty eyes?"
	
	DESCRIBE.SNOWMONG = "Cold Digger!"
	DESCRIBE.SHOCKWORM = "Zzzzt Wiggler!"
	DESCRIBE.ZASPBERRY = "Zzzzt Food"
	DESCRIBE.ICEBOOMERANG = "Make things stop"
	DESCRIBE.MINOTAUR_BOULDER = "Big rock"
	DESCRIBE.MINOTAUR_BOULDER_BIG = "Hm... Hit head on big rock?"
	DESCRIBE.VETERANSHRINE = "Sad head?"
	DESCRIBE.SNOWBALL_THROWABLE = "Fun?"
	DESCRIBE.RAT_TAIL = "Small black butt"
	DESCRIBE.PLAGUEMASK = "Bird face"
	DESCRIBE.SPIDER_TRAPDOOR = "No hair on leggy bug?"
	DESCRIBE.TRAPDOOR = "More friend hair"
	DESCRIBE.HOODEDTRAPDOOR = "Rock"
	DESCRIBE.WICKER_TENTACLE = "Wigglers sick?"
	DESCRIBE.HONEY_LOG = "Me, becomes me"

	DESCRIBE.BUSHCRAB = "Friend? Yes... no?"
	DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
	DESCRIBE.DISEASECUREBOMB = "Cure friends!"
	DESCRIBE.SHROOM_SKIN_FRAGMENT = "Can't chew"
	DESCRIBE.AIR_CONDITIONER = "No more happy time?"
	DESCRIBE.SPOREPACK = "What wrong?"
	DESCRIBE.SALTPACK = "Taste funny"
	
	DESCRIBE.SCORPION = "Stabby bzzter"
	DESCRIBE.SCORPIONCARAPACE = "Is crunchy bzzter"
	DESCRIBE.SCORPIONCARAPACECOOKED = "Burnt bzzter"
	DESCRIBE.HARDSHELLTACOS = "Remembering Home"
	
	DESCRIBE.SKELETONMEAT = "Mmmm, chewy"
	DESCRIBE.CHIMP = DESCRIBE.MONKEY
	DESCRIBE.SWILSON = "Help."
	DESCRIBE.VAMPIREBAT = "Flying claws"
								
	--Swampyness
	DESCRIBE.RICEPLANT = "Water friend!"
	DESCRIBE.RICE = "Water friend babies"
	DESCRIBE.RICE_COOKED = "Sniff"
	DESCRIBE.SEAFOODPAELLA = "Sniff Sniff"
	DESCRIBE.LICELOAF = "Lots of water friend babies"
	DESCRIBE.SUNGLASSES = "Fire ball blockers"
	
	DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
	DESCRIBE.CRITTERLAB_REAL_BROKEN = "Moon rock make good home"
	DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.FIRECRACKERS
	DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
	DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
	DESCRIBE.BUGZAPPER = "Bzzter Basher"
	DESCRIBE.STUMPLING = "Small friend not happy."
	DESCRIBE.MOON_TEAR = "Home sick..."
	DESCRIBE.SHADOW_TELEPORTER = "Friend gift?"
	DESCRIBE.POLLENMITEDEN = "Not friends"
	DESCRIBE.POLLENMITES = "Go away"
    DESCRIBE.SHADOW_CROWN = "Hurts more, but go faster?"
    DESCRIBE.RNEGHOST = DESCRIBE.GHOST
	DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
	DESCRIBE.LUREPLAGUE_RAT = "Friend grow in hairy stuff stealer"
	DESCRIBE.MARSH_GRASS = "Friend."
	DESCRIBE.CURSED_ANTLER = "Big bash stick"
	DESCRIBE.BERNIEBOX = "Trapped inside."
	DESCRIBE.HOODED_FERN = DESCRIBE.CAVE_FERN
	DESCRIBE.HOODEDWIDOW = "Can eat anything"
	DESCRIBE.GIANT_TREE = "Big friend?"
	DESCRIBE.WIDOWSGRASP = "Leggy Leg"
	DESCRIBE.WEBBEDCREATURE = "Leggy bug goodies?"
	ANNOUNCE.WEBBEDCREATURE = "Need leggy stabby"
	DESCRIBE.SNAPDRAGON_BUDDY = "Hungry friend."
	DESCRIBE.SNAPDRAGON = "Big friend! Big belly!"
	DESCRIBE.SNAPPLANT = "Looking good!"
	DESCRIBE.WHISPERPOD = "Need some dirt?"
	DESCRIBE.WHISPERPOD_NORMAL_GROUND =
	{
		GENERIC = "Plant seed.",
		GROWING = "Almost there!",
	}
	DESCRIBE.FRUITBAT = "Flying friend."
	DESCRIBE.PITCHERPLANT = "Hanging friend."
	DESCRIBE.APHID = "Eating big friends!"
	DESCRIBE.GIANT_TREE_INFESTED = "Big friend is sick"
	DESCRIBE.GIANT_BLUEBERRY = "Yay! Water!"
	DESCRIBE.STEAMEDHAMS = "Egads!"
	DESCRIBE.BLUEBERRYPANCAKES = "Yummy boom juice"
	DESCRIBE.SIMPSALAD = "Need more than this"
	DESCRIBE.BEEFALOWINGS = "Crunch"
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "No more push"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "Uh oh, push again"
	DESCRIBE.WIDOWSHEAD = "Bigger leggy head."
	DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
	DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
	DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
	DESCRIBE.WATERMELON_LANTERN = "Nice smile"
	
		--Viperstuff Quotes
	DESCRIBE.VIPERWORM = "Makes head feel funny"
	DESCRIBE.VIPERFRUIT = "Swirly"
	DESCRIBE.VIPERJAM = "Home for friends"
	
	
	DESCRIBE.BLUEBERRYPLANT =         
		{
            READY = "Boom fruit",
			REGROWING = "Grow!",
		}
	DESCRIBE.BERNIE_INACTIVE =
        {
            BROKEN = "What happened?",
            GENERIC = "Hello, Squishy Friend!",
            ASHLEY_BROKEN = "What happened?",
            ASHLEY = "Hello, Squishy Friend!",
        }
	
	DESCRIBE.BERNIE_ACTIVE =
        {
            GENERIC = "Yay! Squishy Friend can play!",
            ASHLEY = "Yay! Squishy Friend can play!",
        }
	DESCRIBE.BERNIE_BIG =
        {
            GENERIC = "Big Squishy Friend!",
            ASHLEY = "Big Squishy Friend!",
        }
	DESCRIBE.ANTIHISTAMINE = "Sniff food"
    ANNOUNCE.CURSED_ITEM_EQUIP = "No good!"
	DESCRIBE.SCREECHER_TRINKET = "Scary, not friend"
	ACTIONFAIL.GIVE = {NOTNIGHT = "Needs moon"}

	DESCRIBE.MAGMAHOUND = "Bad! Bad!"
	DESCRIBE.LIGHTNINGHOUND = "Zzzt woofer!"
	DESCRIBE.RNESKELETON = "Alive. Friend?"
	DESCRIBE.RAT_WHIP = "Chewy"
	DESCRIBE.KLAUS_AMULET = "Feel strong"
	DESCRIBE.CRABCLAW = "Snip snip snip" --Generic line for now, this is unimplemented
	DESCRIBE.RAT_MASK = "Who knew treasure was so smelly?" --Generic line for now, this is unimplemented

	DESCRIBE.ORANGE_VOMIT = "Taste funny"
	DESCRIBE.GREEN_VOMIT = "Taste funny"
	DESCRIBE.RED_VOMIT = "Taste funny"
	DESCRIBE.PINK_VOMIT = "Taste funny"
	DESCRIBE.YELLOW_VOMIT = "Taste funny"
	DESCRIBE.PURPLE_VOMIT = "Taste funny"
	DESCRIBE.PALE_VOMIT = "Taste funny"
	
	DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
	DESCRIBE.PIGKING_PIGGUARD = 
	{
	GUARD = DESCRIBE.PIGMAN.GUARD,
	WEREPIG = DESCRIBE.PIGMAN.WEREPIG,
	}
	
	DESCRIBE.BIGHT = "Kzzzrt"
	DESCRIBE.KNOOK = "Ka-thunk, Ka-thunk"
	DESCRIBE.ROSHIP = "Ker-chew"
	
	DESCRIBE.UM_PAWN = "Nope"
	DESCRIBE.UM_PAWN_NIGHTMARE = ""

	DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
	DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
	DESCRIBE.CAVE_EXIT_SUNKDECID= DESCRIBE.CAVE_EXIT
	
	DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH	
	-- Blowgun stuff
	DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
	DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
	DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
	DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
	DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW
