
ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WORMWOOD
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WORMWOOD.DESCRIBE

--	[ 		Wormwood Descriptions		]	--

GLOBAL.STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_WINONAGEN = "Did I do an oopsie?"