
ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WORTOX
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WORTOX.DESCRIBE

--	[ 		Wortox Descriptions		]	--

GLOBAL.STRINGS.CHARACTERS.WORTOX.ANNOUNCE_WINONAGEN = "What's this supposed to do?"