ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WURT
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WURT.DESCRIBE

--	[ 		Wurt Descriptions		]	--
	DESCRIBE.DEERCLOPS = "He not look happy, florp."
    ANNOUNCE.ANNOUNCE_HARDCORE_RES = "Not go in there, florp."
    ANNOUNCE.ANNOUNCE_WINONAGEN = "Weeno-lady need to do it!"
    ANNOUNCE.ANNOUNCE_RATRAID = "What that squeak?"
    ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "Sneaky things!"
    ANNOUNCE.ANNOUNCE_RATRAID_OVER = "Little meanies take stuff! Follow! Get!"
    ANNOUNCE.ANNOUNCE_ACIDRAIN = {
        "Ow! Burny rain!",
        "Hurting! Rain hurting!",
        "Ow! This rain bad!",
    }
    ANNOUNCE.ANNOUNCE_TOADSTOOLED = "Aah! Mushies! Big mushies!"
	--FoodBuffs
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "ssSsooo cCccold"
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "F-florp!!"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "Feeling better now"
	--FoodBuffs
	ANNOUNCE.ANNOUNCE_RNEFOG = "Stop looking!!"
    DESCRIBE.UNCOMPROMISING_RAT = "Spiderfolk family? Have hair."
    DESCRIBE.UNCOMPROMISING_RATHOLD = "Little eyes in hole! Hello!"
    DESCRIBE.RATPOISONBOTTLE = "Veggies but taste really bad."
    DESCRIBE.RATPOISON = "Spill! Wasn't good anyway."

    DESCRIBE.MONSTERSMALLMEAT = "No, not good. Leave for Spiderfolk?"
    DESCRIBE.COOKEDMONSTERSMALLMEAT = "Glurgh! Smell so bad."
    DESCRIBE.MONSTERSMALLMEAT_DRIED = "Even bader now, florpt!"

    DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "Mushroom? Mad mushroom!"
    DESCRIBE.TOADLING = "Veggie...froggie? Not sure if ok to eat."
	
    DESCRIBE.GASMASK = "Smell bad, smells bad."
	DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
	DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
	DESCRIBE.SPIDERQUEENCORPSE = "Like the smell!"
	ANNOUNCE.ANNOUNCE_SNEEZE = "Choo! Egh."
	ANNOUNCE.ANNOUNCE_HAYFEVER = "Nose feel funny!"
	ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "Nose feels good again!"
	ANNOUNCE.ANNOUNCE_FIREFALL = {
		"Bllrgh, is scary!",
		"Anty angry!",
		"Groundy fire! Florp!",
	}
	ANNOUNCE.ANNOUNCE_ROOTING = "Stuck!"
	DESCRIBE.SAND = "Grainy stuffs."
	DESCRIBE.SANDHILL = "Itch on scales..."
	DESCRIBE.SNOWPILE = "Fun! Brr..."
	DESCRIBE.SNOWGOGGLES = "Silly eyes on silly hat!"
	
	DESCRIBE.SNOWMONG = "Not fun!!!"
	DESCRIBE.SHOCKWORM = "Sparky Worm!!"
	DESCRIBE.ZASPBERRY = "Raps-perry?"
	DESCRIBE.ICEBOOMERANG = "This is fun, florp!"
	SNOWBALL_THROWABLE = "Why you throw at us!?"
	DESCRIBE.VETERANSHRINE = "I hate it, florp!"
	DESCRIBE.RAT_TAIL = "It feels good to rub on face, florp!"
	DESCRIBE.PLAGUEMASK = "I don't like it! It's scary, florp!"
	DESCRIBE.SPIDER_TRAPDOOR = "Is it naked?"
	DESCRIBE.TRAPDOOR = "I see nothing!"
	DESCRIBE.WICKER_TENTACLE = "Wiggler don't look normal... sick?"
	DESCRIBE.HONEY_LOG = "Flrbbl... not alive is it?"

	DESCRIBE.BUSHCRAB = "Crabby!"
	DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
	DESCRIBE.DISEASECUREBOMB = "Plant make snacks in no time!"
	DESCRIBE.SHROOM_SKIN_FRAGMENT = "Smell like me!"
	DESCRIBE.AIR_CONDITIONER = "Smells weird, florp."
	DESCRIBE.SPOREPACK = "Smells like home!"
	DESCRIBE.SALTPACK = "Eyes hurt!"
	DESCRIBE.SCORPION = "Look like spiderfolk?"
	DESCRIBE.SKELETONMEAT = "Whats problem?"
	DESCRIBE.CHIMP = DESCRIBE.MONKEY
	DESCRIBE.SWILSON = "Scary Shadow, Florp."
	DESCRIBE.VAMPIREBAT = "Bigger! Grrr!"
	DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
	DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.FIRECRACKERS