
ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WX78
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE

--	[ 		WX78 Descriptions		]	--
<<<<<<< Updated upstream
=======
	
	ANNOUNCE.ANNOUNCE_RATRAID = "A VIRUS IS INSTALLING"
	ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "DESTRUCTION MODE : ENABLED"
	ANNOUNCE.ANNOUNCE_RATRAID_OVER = "I HAVE TO DESTROY THEY'RE BASE"
	
	DESCRIBE.UNCOMPROMISING_RAT = "POTENTIALLY INFECTED"
>>>>>>> Stashed changes
