ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WX78
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE

--	[ 		WX78 Descriptions		]	--

    ANNOUNCE.ANNOUNCE_HARDCORE_RES = "UNABLE TO ESTABLISH CONNECTION"
    ANNOUNCE.ANNOUNCE_WINONAGEN = "ERROR: PROCESS UNDEFINED"
    ANNOUNCE.ANNOUNCE_RATRAID = "DOES SOMEONE REQUIRE OIL?"
    ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "YOU'RE NOT ROBOTS. I FEEL SO BETRAYED RIGHT NOW"
    ANNOUNCE.ANNOUNCE_RATRAID_OVER = "ANNOYING HAIR DRONES DISENGAGING"
    ANNOUNCE.ANNOUNCE_ACIDRAIN = {
        "WARNING: HULL INTEGRITY AT RISK",
        "AS IF NON-ACIDIC WATER WASN'T BAD ENOUGH",
        "ABNORMALLY COROSIVE LIQUIDS DETECTED",
    }
    ANNOUNCE.ANNOUNCE_TOADSTOOLED = "ADVISORY: THE FLORA IS IN A GOOD MOOD TODAY"
	--FoodBuffs
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "ssSsooo cCccold"
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "ERROR: HULL INTEGRITY COMPROMISED"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "Feeling better now"
	--FoodBuffs
	
	--CaliforniaKing
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "NASAL UNIT CLEANING IN PROCESS"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "NASAL UNIT DEBRIS REACCUMULATING"
	DESCRIBE.CALIFORNIAKING = "HIGHLY IRRATIVE COMPOUND CAN CLEAR NASAL UNIT"
	--CaliforniaKing
	
	ANNOUNCE.ANNOUNCE_RNEFOG = "WARNING: PREDICTIBILITY FACTOR COMPROMISED"
    DESCRIBE.UNCOMPROMISING_RAT = "DISGUSTING ORGANIC RETRIEVAL DRONES"
    DESCRIBE.UNCOMPROMISING_RATHOLD = "VERMIN REPOSITORY"
    DESCRIBE.RATPOISONBOTTLE = "ATTENTION DISGUSTING ORGANICS: I HAVE A VERY SAFE PRESENT FOR YOU"
    DESCRIBE.RATPOISON = "NOW LAP IT UP, LESSER CREATURES"

    DESCRIBE.MONSTERSMALLMEAT = "IT'S WHAT'S ON THE INSIDE THAT COUNTS. YOUR INSIDES ARE TERRIBLE"
    DESCRIBE.COOKEDMONSTERSMALLMEAT = "THIS FUEL SOURCE IS HIGHLY INEFFICIENT"
    DESCRIBE.MONSTERSMALLMEAT_DRIED = "DEHYDRATED PROTEINS"

    DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "TOXIN EXHAUST PORT LOCATED"
    DESCRIBE.TOADLING = "TERRITORIAL FUEL IS STILL FUEL"
	
    DESCRIBE.GASMASK = "AIR FILTER UNIT ACQUIRED"
	DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
	DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
	DESCRIBE.SPIDERQUEENCORPSE = "THE CORPSE OF A DISGUSTING INSECT"
	ANNOUNCE.ANNOUNCE_SNEEZE = "01000001 01000011 01001000 01001111 01001111"
	ANNOUNCE.ANNOUNCE_HAYFEVER = "ERROR. ENVIRONMENTAL DETRITUS CLOGGING NASAL UNIT"
	ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "DETRITUS HAS CLEARED FROM ENVIRONMENT"
	ANNOUNCE.ANNOUNCE_FIREFALL = {
		"ANOTHER ANGRY FLESHLING",
		"VOLCANIC DISRUPTIONS",
		"FIRE WILL CLEANSE THE WORLD OF ORGANICS. AND ME.",
	}
	ANNOUNCE.ANNOUNCE_ROOTING = "GET THESE ORGANICS OFF ME"
	ANNOUNCE.SHADOWTALKER = {
        "I AM SURROUNDED BY WEAKNESS",
        "THEY ARE ALL AGAINST ME",
        "I AM SUPERIOR TO THE ORGANICS",
    }
	DESCRIBE.SAND = "GRAINS OF DEFEATED ROCK"
	DESCRIBE.SANDHILL = "THE ROCK DUST IS COLLECTING IN PILES"
	DESCRIBE.SNOWPILE = "KEEP THAT AWAY FROM ME"
	DESCRIBE.SNOWGOGGLES = "I HAVE MODIFIED THE FILTH WITH AN OCCULAR ENHANCEMENT"
	
	DESCRIBE.SNOWMONG = "A FROZEN TERROR"
	DESCRIBE.SHOCKWORM = "DANGER: ELECTRICAL HAZARD"
	DESCRIBE.ZASPBERRY = "SYSTEMS READY FOR FULL CHARGE"
	DESCRIBE.ICEBOOMERANG =  "NON-CONSENTUAL COOLING SYSTEM"
	DESCRIBE.SNOWBALL_THROWABLE = "SUBSTANCE NATIVE TO OBNOXIOUS WEATHER."
	DESCRIBE.VETERANSHRINE = "CALCULATING RISK VERSUS REWARD"
	DESCRIBE.RAT_TAIL = "MILLIONS OF MEATSACKS DIED TO A RAT. HA. HA. HA."
	DESCRIBE.PLAGUEMASK = "ANTI-VIRAL FACEPLATE"
	DESCRIBE.SPIDER_TRAPDOOR = "AMBUSHING INSECT"
	DESCRIBE.TRAPDOOR = "THE GROUND."
	DESCRIBE.WICKER_TENTACLE = "THE FILTH IS ROTTING. PATHETIC."
	DESCRIBE.HONEY_LOG = "THIS WILL CLEAR MY NASAL UNIT. SOMEHOW."

	DESCRIBE.BUSHCRAB = "MORE EVIDENCE THAT BIOFORMS ARE UNRELIABLE"
	DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
	DESCRIBE.DISEASECUREBOMB = "I WILL CORRECT NATURES MISTAKES"
	DESCRIBE.TOADLINGSPAWNER = "UH OH"
	DESCRIBE.SHROOM_SKIN_FRAGMENT = "FISTFULLS OF FLESH"
	DESCRIBE.AIR_CONDITIONER = "ARIAL FIREWALL"
	DESCRIBE.SPOREPACK = "IT IS REPULSIVE TO FLESHLINGS. GOOD."
	DESCRIBE.SALTPACK = "I AM THE MECHANICAL KING OF WINTER"
	
	DESCRIBE.SCORPION = "STINGY INSECT UNIT"
	DESCRIBE.SCORPIONCARAPACE = "INSECT BASED FUEL"
	DESCRIBE.SCORPIONCARAPACECOOKED = "FUEL IS STILL HEAVILY POLLUTED"
	DESCRIBE.HARDSHELLTACOS = "CRUNCH"

	DESCRIBE.SKELETONMEAT = "I LOVE IT"
	DESCRIBE.CHIMP = DESCRIBE.MONKEY
	DESCRIBE.SWILSON = "ANOMALY IDENTIFIED"
	DESCRIBE.VAMPIREBAT = "BIGGER FLYING RAT"
										
	--Swampyness
	DESCRIBE.RICEPLANT = "ORGANIC IS SURROUNDED BY HAZARDOUS MATERIAL"
	DESCRIBE.RICE = "IT REQUIRES REFINEMENT"
	DESCRIBE.RICE_COOKED = "THIS WAS NOT WORTH IT"
	DESCRIBE.SEAFOODPAELLA = "THIS MIGHT BE WORTH IT"
	DESCRIBE.LICELOAF = "BLAND FOOD TAKES A LONG TIME TO EXPIRE"
	DESCRIBE.SUNGLASSES = "OPTICAL ENHANCEMENT AQUIRED"
	
	DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
	DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.FIRECRACKERS
	DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
	DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
	DESCRIBE.BUGZAPPER = "ELECTRICAL ATTACHMENT"
	DESCRIBE.STUMPLING = "WARNING: MOBILE STUMP"
	DESCRIBE.MOON_TEAR = "DEATH INCARNATE. LOCK IT AWAY"
	DESCRIBE.SHADOW_TELEPORTER = "ARCANE ENTITIES AT WORK. LET US CRUSH IT"
	DESCRIBE.POLLENMITEDEN = "HOME OF TINY FLYING MEATSACK"
    DESCRIBE.POLLENMITES = "TINY FLYING MEATSACKS"
    DESCRIBE.SHADOW_CROWN = "HEAD BASED ACCELERATOR. WARNING: VULNERABILTIY DETECTED"
    DESCRIBE.RNEGHOST = DESCRIBE.GHOST
	DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS