ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WX78
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE

--	[ 		WX78 Descriptions		]	--
    ANNOUNCE.ANNOUNCE_HARDCORE_RES = "UNABLE TO ESTABLISH CONNECTION"
    ANNOUNCE.ANNOUNCE_WINONAGEN = "ERROR: PROCESS UNDEFINED"
    ANNOUNCE.ANNOUNCE_RATS = "DOES SOMEONE REQUIRE OIL?"
    ANNOUNCE.ANNOUNCE_ACIDRAIN = {
        "WARNING: HULL INTEGRITY AT RISK",
        "AS IF NON-ACIDIC WATER WASN'T BAD ENOUGH",
        "ABNORMALLY COROSIVE LIQUIDS DETECTED",
    }
    ANNOUNCE.ANNOUNCE_TOADSTOOLED = "ADVISORY: THE FLORA IS IN A MOOD TODAY"

    DESCRIBE.RAT = "DISGUSTING ORGANIC RETRIEVAL DRONES"
    DESCRIBE.RAT_BURROW = "VERMIN REPOSITORY"
    
    DESCRIBE.MONSTERSCRAP = "IT'S WHAT'S ON THE INSIDE THAT COUNTS. YOUR INSIDES ARE TERRIBLE"
    DESCRIBE.COOKEDMONSTERSCRAP = "THIS FUEL SOURCE IS HIGHLY INEFFICIENT"
    DESCRIBE.MONSTERSCRAP_DRIED = "DEHYDRATED PROTEINS"
    
    DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "TOXIN EXHAUST PORT LOCATED"
    DESCRIBE.TOADLING = "TERRITORIAL FUEL IS STILL FUEL"
	
	ANNOUNCE.ANNOUNCE_RATRAID = "A VIRUS IS INSTALLING"
	ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "DESTRUCTION MODE : ENABLED"
	ANNOUNCE.ANNOUNCE_RATRAID_OVER = "I HAVE TO DESTROY THEIR BASE"
	
	DESCRIBE.UNCOMPROMISING_RAT = "POTENTIALLY INFECTED"