ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WX78
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WX78.DESCRIBE

--	[ 		WX78 Descriptions		]	--

    ANNOUNCE.ANNOUNCE_HARDCORE_RES = "UNABLE TO ESTABLISH CONNECTION"
    ANNOUNCE.ANNOUNCE_WINONAGEN = "ERROR: PROCESS UNDEFINED"
    ANNOUNCE.ANNOUNCE_RATRAID = "DOES SOMEONE REQUIRE OIL?"
    ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "YOU'RE NOT ROBOTS. I FEEL SO BETRAYED RIGHT NOW"
    ANNOUNCE.ANNOUNCE_RATRAID_OVER = "ANNOYING HAIR DRONES DISENGAGING"
    ANNOUNCE.ANNOUNCE_ACIDRAIN = {
        "WARNING: HULL INTEGRITY AT RISK",
        "AS IF NON-ACIDIC WATER WASN'T BAD ENOUGH",
        "ABNORMALLY COROSIVE LIQUIDS DETECTED",
    }
    ANNOUNCE.ANNOUNCE_TOADSTOOLED = "ADVISORY: THE FLORA IS IN A MOOD TODAY"

    DESCRIBE.UNCOMPROMISING_RAT = "DISGUSTING ORGANIC RETRIEVAL DRONES"
    DESCRIBE.UNCOMPROMISING_RATHOLD = "VERMIN REPOSITORY"
    DESCRIBE.RATPOISONBOTTLE = "ATTENTION DISGUSTING ORGANICS: I HAVE A VERY SAFE PRESENT FOR YOU"
    DESCRIBE.RATPOISON = "NOW LAP IT UP, LESSER CREATURES"

    DESCRIBE.MONSTERSCRAP = "IT'S WHAT'S ON THE INSIDE THAT COUNTS. YOUR INSIDES ARE TERRIBLE"
    DESCRIBE.COOKEDMONSTERSCRAP = "THIS FUEL SOURCE IS HIGHLY INEFFICIENT"
    DESCRIBE.MONSTERSCRAP_DRIED = "DEHYDRATED PROTEINS"

    DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "TOXIN EXHAUST PORT LOCATED"
    DESCRIBE.TOADLING = "TERRITORIAL FUEL IS STILL FUEL"