return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "I'd better wait until it's asleep.",
			GENERIC = "I'd better not...",
			NOBITS = "He's naked!",
		},
		REPAIR =
        {
            WRONGPIECE = "Um, no... that seems wrong.",
        },
        BUILD =
        {
            MOUNTED = "I could, but I would rather be on the ground.",
            HASPET = "All good on pets at the moment, thanks.",
        },
		STORE =
		{
			GENERIC = "Not a chance!",
			NOTALLOWED = "I can't do that!",
		},
		RUMMAGE =
		{	
			GENERIC = "I can't do that.",
			INUSE = "I'll just wait my turn then...",
		},
		USEKLAUSSACKKEY =
        {
        	WRONGKEY = "Whoops! That wasn't right.",
        	KLAUS = "Not while I'm being harassed, maybe?!",
        },
        COOK =
        {
            GENERIC = "I can't cook right now.",
            INUSE = "Too many cooks? Yeah, too many...",
            TOOFAR = "It's too far away!",
        },
        GIVE =
        {
            GENERIC = "That doesn't go there.",
            DEAD = "I'll just...wait.",
            SLEEPING = "Hey could you...? Um, nevermind, I'll let you sleep.",
            BUSY = "I'll try again in a second.",
            ABIGAILHEART = "I tried my best.",
            GHOSTHEART = "Not the greatest of ideas.",
            NOTGEM = "I don't think that would fit!",
            WRONGGEM = "This isn't the right gem.",
            NOTSTAFF = "It's just not the right size.",
            MUSHROOMFARM_NEEDSSHROOM = "A mushroom would probably be of more use.",
            MUSHROOMFARM_NEEDSLOG = "Need's a log. A living one, preferably.",
            SLOTFULL = "We already put something there.",
            DUPLICATE = "We already know that one.",
            NOTSCULPTABLE = "That sculptures a bust...",
            NOTATRIUMKEY = "It's not quite the right shape.",
            CANTSHADOWREVIVE = "It won't resurrect.",
            WRONGSHADOWFORM = "I think it's been built incorrectly.",
        },
        GIVETOPLAYER =
        {
            FULL = "Your pockets are too full!",
            DEAD = "I'll just...wait.",
            SLEEPING = "Um, nevermind, I'll let you sleep.",
            BUSY = "I'll try again in a second.",
        },
        WRITE =
        {
            GENERIC = "I think it's fine as is.",
            INUSE = "I'll draw over it later.",
        },
        DRAW =
        {
            NOIMAGE = "I think I'd do better with an example.",
        },
        ATTUNE =
        {
            NOHEALTH = "I don't feel so good... I'll try later...",
        },
	},
	ACTIONFAIL_GENERIC = "That could have gone better.",
	ANNOUNCE_DIG_DISEASE_WARNING = "Like pulling weeds...",
	ANNOUNCE_PICK_DISEASE_WARNING = "I've seen some nasty plants in my life, but this takes the cake.",
	ANNOUNCE_ADVENTUREFAIL = "Stupid, STUPID Maxwell! I'll beat you this time!",
	ANNOUNCE_BEES = "Bees? BEES!",
	ANNOUNCE_BOOMERANG = "I thought it would hit me...",
	ANNOUNCE_CHARLIE = "EEK! What is that?!",
	ANNOUNCE_CHARLIE_ATTACK = "NO, NO, NO, NO! L-leave me alone!",
	ANNOUNCE_COLD = "S-So... c-c-cold...!",
	ANNOUNCE_HOT = "So... h-hot...",
	ANNOUNCE_CRAFTING_FAIL = "I must have forgotten something...",
	ANNOUNCE_DEERCLOPS = "S...Something big is coming...",
	ANNOUNCE_DUSK = "It's getting dark! I better set up camp...",
	ANNOUNCE_CAVEIN = "Everything is s-shaking!",
	ANNOUNCE_ANTLION_SINKHOLE = 
	{
		"Earthquake! Save the flowers!",
		"Earthquake! Save the animals!",
		"Earthquake! Save me!",
	},
	ANNOUNCE_ANTLION_TRIBUTE =
	{
        "Take this, and please leave me alone!",
        "Hope this will do...",
        "Now stop taking your anger out on the earth...",
	},
	ANNOUNCE_EAT =
	{
		GENERIC = "It's food!",
		PAINFUL = "I should have known that was no good...!",
		SPOILED = "Yuck! It's completely rotten!",
		STALE = "It's stale, but it's still edible...",
	},
	ANNOUNCE_ENCUMBERED =
    {
        "Oh... Geez...",
        "Where's Wolfgang when you need him...",
        "Legs... don't fail me now...!",
        "Harder... than... pulling... weeds...",
        "This... isn't... worth it!",
        "Good... exercise... heh...",
        "Oof...!",
        "Pant... Pant...",
        "Never... AGAIN...",
    },
    ANNOUNCE_SNARED = "I'm in the bone zone! I'M IN THE BONE ZONE!",
	ANNOUNCE_ENTER_DARK = "This is a REALLY bad idea!",
	ANNOUNCE_ENTER_LIGHT = "I should be safe here.",
	ANNOUNCE_FREEDOM = "F-Freedom! I'm free!",
	ANNOUNCE_HOUNDS = "Oh no! H-Hounds!",
	ANNOUNCE_HUNGRY = "I'm so hungry...",
	ANNOUNCE_HUNT_BEAST_NEARBY = "It's not far from here!",
	ANNOUNCE_HUNT_LOST_TRAIL = "Oh no! I've lost track of it...",
	ANNOUNCE_INV_FULL = "I'm carrying too much!",
	ANNOUNCE_KILLERBEES = "The only thing worse than bees are killer bees...",
	ANNOUNCE_KNOCKEDOUT = "N-Not again... How long have I been out...?",
	ANNOUNCE_MOSQUITOS = "I hate mosquitoes.",
	ANNOUNCE_NODANGERSLEEP = "I can't sleep now! Th-they're nearby...",
	ANNOUNCE_NODAYSLEEP = "I'm not sleeping when the sun's still up!",
	ANNOUNCE_NOHUNGERSLEEP = "I don't want to sleep on an empty stomach.",
	ANNOUNCE_PECKED = "Ow! Stupid bird!",
	ANNOUNCE_QUAKE = "W-What's g-going on--?!",
	ANNOUNCE_THORNS = "Ouch! It pricked me!",
	ANNOUNCE_TORCH_OUT = "Oh no! No, no, no! I need light!",
	ANNOUNCE_TRAP_WENT_OFF = "I hope I caught something tasty.",
	ANNOUNCE_UNIMPLEMENTED = "No thanks.",
	ANNOUNCE_WORMHOLE = "Oof, my head...",
	ANNOUNCE_CANFIX = "I think I can fix this!",

	ANNOUNCE_TOOL_SLIP = "Aaand there it goes.",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "EEK! ...That was close!",

	ANNOUNCE_DAMP = "My apron is getting wet...",
	ANNOUNCE_WET = "Now im all wet...",
	ANNOUNCE_WETTER = "I need to get out of the rain!",
	ANNOUNCE_SOAKED = "I am LITERALLY soaked to the bone.",
	
	ANNOUNCE_BECOMEGHOST = "oOoo? OooOoo...",
	ANNOUNCE_GHOSTDRAIN = "My humanity is about to start slipping away...",
	ANNOUNCE_PETRIFED_TREES = "Stone trees huh? That's... nice...?",
	ANNOUNCE_KLAUS_ENRAGE = "I made it mad! I don't like it!",
	ANNOUNCE_KLAUS_UNCHAINED = "It's no longer held back!!",
	ANNOUNCE_KLAUS_CALLFORHELP = "It's calling it's friends!",

	DESCRIBE_SAMECHARACTER = "Is that a mirror?",

	BATTLECRY =
	{
		GENERIC = "Sorry for this!",
		PIG = "I'm so Sorry! I-It's you or me!",
		PREY = "Get back here!",
		BEE = "Please don't sting me, please don't sting me!",
		KILLERBEE = "THIS IS THE WORST IDEA!",
		MOSQUITO = "You're not getting MY blood, freaks!",
		SPIDER = "EEK! You're not Warren!",
		SPIDER_WARRIOR = "WHY IS IT SO BIG?!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "It got away...",
		PIG = "No pork tonight...",
		PREY = "Aw, man! I'll get it next time...",
		SPIDER = "I-Is it gone?!",
		SPIDER_WARRIOR = "Somehow, I think that was the better outcome...",
	},
	
	DESCRIBE =
	{
		MULTIPLAYER_PORTAL = "It's a step up from the last one...",
		ANTLION = 
		{
			GENERIC = "I think it wants something?",
			VERYHAPPY = "So, you'll stop wrecking my gardens, right?",
			UNHAPPY = "It looks mad.",
		},
		ANTLIONTRINKET = "I'm sure someone will like this.",
		SANDSPIKE = "I'm suddenly less worried about sand in my shoes!",
        SANDBLOCK = "Psht, I could do better...",
        GLASSSPIKE = "Memories of the time I wasn't skewered.",
        GLASSBLOCK = "Fire does some amazing things...",
		EEL = "It's a water snake!",
		EEL_COOKED = "Mmm, it smells good.",
		MOLE =
		{
			HELD = "I can feel it's little nose sniffing me!",
			UNDERGROUND = "Dig your life away, little friend.",
			ABOVEGROUND = "That nose looks like it would tickle.",
		},
		PLAYER =
        {
            GENERIC = "Greetings, %s!",
            ATTACKER = "%s looks shifty...",
            MURDERER = "Murderer!",
            REVIVER = "%s, friend of ghosts.",
            GHOST = "%s could use a heart.",
        },
		WILSON = 
		{
			GENERIC = "%s, the science guy!",
			ATTACKER = "%s looks shifty...",
            MURDERER = "Murderer!",
            REVIVER = "%s, friend of ghosts.",
            GHOST = "%s could use a heart.",
		},
		WOLFGANG = 
		{
			GENERIC = "%s! Hey there big guy.",
			ATTACKER = "%s looks shifty...",
            MURDERER = "Murderer!",
            REVIVER = "%s, friend of ghosts.",
            GHOST = "%s could use a heart.",
		},
		WAXWELL = 
		{
			GENERIC = "Oh, it's %s...",
			ATTACKER = "%s looks shifty...",
            MURDERER = "Murderer!",
            REVIVER = "%s, friend of ghosts.",
            GHOST = "%s could use a heart.",
		},
		WX78 = 
		{
			GENERIC = "Uh, beep boop, %s?",
			ATTACKER = "%s looks shifty...",
            MURDERER = "Murderer!",
            REVIVER = "%s, friend of ghosts.",
            GHOST = "%s could use a heart.",
		},
		WILLOW = 
		{
			GENERIC = "Uh, hi, %s.",
			ATTACKER = "%s looks shifty...",
            MURDERER = "Murderer!",
            REVIVER = "%s, friend of ghosts.",
            GHOST = "%s could use a heart.",
		},
		WENDY = 
		{
			GENERIC = "Uh, hi, %s.",
			ATTACKER = "%s looks shifty...",
            MURDERER = "Murderer!",
            REVIVER = "%s, friend of ghosts.",
            GHOST = "%s could use a heart.",
		},
		WOODIE = 
		{
			GENERIC = "Uh, hi, %s.",
			ATTACKER = "%s looks shifty...",
            MURDERER = "Murderer!",
            REVIVER = "%s, friend of ghosts.",
            GHOST = "%s could use a heart.",
		},
		WICKERBOTTOM = 
		{
			GENERIC = "Good day, %s!",
			ATTACKER = "%s looks shifty...",
            MURDERER = "Murderer!",
            REVIVER = "%s, friend of ghosts.",
            GHOST = "%s could use a heart.",
		},
		WES = 
		{
			GENERIC = "Not much on small talk, %s? Me neither...",
			ATTACKER = "%s looks shifty...",
            MURDERER = "Murderer!",
            REVIVER = "%s, friend of ghosts.",
            GHOST = "%s could use a heart.",
		},
		WEBBER = 
		{
			GENERIC = "Ah-! I mean, hello %s...",
			ATTACKER = "%s looks shifty...",
            MURDERER = "Murderer!",
            REVIVER = "%s, friend of ghosts.",
            GHOST = "%s could use a heart.",
		},
		WATHGRITHR = 
		{
			GENERIC = "Uh, hi, %s.", 
			ATTACKER = "%s looks shifty...",
            MURDERER = "Murderer!",
            REVIVER = "%s, friend of ghosts.",
            GHOST = "%s could use a heart.",
		},
		MOLEHILL = "There are some rocks down there.",
		UNAGI = "Huh. It's edible, at any rate.",
		EYETURRET = "This is going to be awesome.",
		EYETURRET_ITEM = "I have to set it down first!",
		MINOTAURHORN = "A minotaur horn-- Rare, but useful in many remedies.",
		THULECITE_PIECES = "How curious!",
		POND_ALGAE = "This is an excellent dietary protein.",
		GREENSTAFF = "It goes ZAP when there's stuff.",
		POTTEDFERN = "Ahh, lovely.",
		THULECITE = "I think it's some sort of mineral...",
		SENTRYWARD = "Keep an eye on things, okay?",
		ARMORRUINS = "Looks heavy, but sturdy.",
		RUINS_BAT = "Sweet, it's a bat!",
		BISHOP_NIGHTMARE = "W-What is THAT?!",
		ROOK_NIGHTMARE = "I don't like this...",
		KNIGHT_NIGHTMARE = "It looks broken but d-deadly...",
		MINOTAUR = "REALLY, MAXWELL?! A MINOTAUR?!",
		SPIDER_DROPPER = "EEK! Dropping spiders!",
		NIGHTMARELIGHT = "I don't want to stay around THIS light...",
		GREENGEM = "This feels magical.",
		RELIC = "Curious.",
		RUINS_RUBBLE = "I wonder if I can fix this...",
		RUBBLE = "It's all smashed to bits",
		MULTITOOL_AXE_PICKAXE = "It does the job of a thousand!",
		ORANGESTAFF = "I can teleport with this! Catch me if you can!",
		YELLOWAMULET = "I should be careful with this...",
		GREENAMULET = "Now THIS is an amulet I can appreciate.",
		SLURPER = "Cute but a SERIOUS headache.",
		SLURPER_PELT = "Karma.",
		ARMORSLURPER = "...Armor, I guess?",
		ORANGEAMULET = "All the rewards of gathering without the work!",
		YELLOWSTAFF = "I can make a fire with this!",
		YELLOWGEM = "Shiny!",
		ORANGEGEM = "It's pretty!",
		TELEBASE = 
		{
			VALID = "It's ready!",
			GEMS = "It's not ready yet!",
		},
		GEMSOCKET = 
		{
			VALID = "All set!",
			GEMS = "It won't work without a gem!",
		},
		STAFFLIGHT = "Sanity in a stick!",
        ANCIENT_ALTAR = "It looks like some sort of altar.",
		ANCIENT_ALTAR_BROKEN = "It's broken...",
        ANCIENT_STATUE = "Creepy...",
		LICHEN = "Lichen! Useful in potions and as food.",
		CUTLICHEN = "It's Lichen!",
		CAVE_BANANA = "Bananas!",
		CAVE_BANANA_COOKED = "After everything I've eaten here, this is a delicacy.",
		CAVE_BANANA_TREE = "A cave banana tree...? Why not.",
		ROCKY = "Maybe it's friendly...?",
		
		COMPASS =
		{
			GENERIC="Which way am I facing?",
			N = "Never!",
			S = "Sour!",
			E = "Eat!",
			W = "Wheat!",
			NE = "Neast!",
			SE = "Seast!",
			NW = "Nwest!",
			SW = "Swest!",
		},
		
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "It's normal.",
			WARN = "Uh oh...",
			WAXING = "It's getting worse...",
			STEADY = "It's steady now...!",
			WANING = "It's fading!",
			DAWN = "Almost gone!",
			NOMAGIC = "It's not responding at all.",
		},
		
		HOUNDSTOOTH="I don't know HOW I got this.",
		ARMORSNURTLESHELL="Safety first!",
		BAT="It's a bat!",
		BATBAT = "This is probably the weirdest thing I've made.",
		BATWING="A bat wing. Despite stories, it's actually horrible in remedies.",
		BATWING_COOKED="Can I eat this?",
		BEDROLL_FURRY="True luxury here!",
		BUNNYMAN="How curious!",
		FLOWER_CAVE="It's a cave flower!",
		FLOWER_CAVE_DOUBLE="Double flowers, all the way!",
		FLOWER_CAVE_TRIPLE="Oooh, how lovely.",
		GUANO="It's bat poop.",
		LANTERN="This is handy!",
		LIGHTBULB="I haven't seen one of these in... Uh, a while.",
		MANRABBIT_TAIL="For good luck.",
		MUSHTREE_TALL  ="It's a mushroom tree!",
		MUSHTREE_MEDIUM="An herbalist's dream.",
		MUSHTREE_SMALL ="This one's cute!",
		RABBITHOUSE="What a sweet little house!",
		SLURTLE="What-- you know what? I'm not even surprised anymore.",
		SLURTLE_SHELLPIECES="Aww, it broke.",
		SLURTLEHAT="Safety first!",
		SLURTLEHOLE="Slurtles live here.",
		SLURTLESLIME="I'm not sure even I can find a use for this goo!",
		SNURTLE="Oh! This one's different!",
		SPIDER_HIDER="I have to wait until it's out of its shell to hit it...",
		SPIDER_SPITTER="It spits things. I HATE spiders.",
		SPIDERHOLE="A spider hole. Nooo thank you.",
		STALAGMITE="It's a Stalagmite.",
		STALAGMITE_FULL="This one's big!",
		STALAGMITE_LOW="Stalittlemite.",
		STALAGMITE_MED="This one's only half grown.",
		STALAGMITE_TALL="This one's bigger!.",
		STALAGMITE_TALL_FULL="Wow!",
		STALAGMITE_TALL_LOW="Tall, but low.",
		STALAGMITE_TALL_MED="I'll name it Jeffrey.",
		TURF_FUNGUS="The ground is made of fungi...",
		TURF_MUD="Eyuch! Mud.",
		TURF_SINKHOLE="It's a sinkhole!",
		TURF_UNDERROCK="It's super rocky.",	

		POWCAKE = "Uh... I'm suddenly not hungry.",
        CAVE_ENTRANCE = 
        {
            GENERIC="I think it's blocking something.",
            OPEN = "There's a huge cavern in there!",
        },
        CAVE_EXIT = "Well... I'm alive, at any rate.",	
		MAXWELLPHONOGRAPH = "I would have expected something more spooky.",
		BOOMERANG = "I'll be honest; I'm probably going to hurt myself.",
		PIGGUARD = "He looks aggressive...",
		ADVENTURE_PORTAL = "AHA! This should take me right to that egomaniac!",
		AMULET = "I... I don't like this... Not after last time...",
		ANIMAL_TRACK = "Oh, these tracks are fresh!",
		ARMORGRASS = "It's something, at least.",
		ARMORMARBLE = "How am I supposed to move in this?!",
		ARMORWOOD = "It's effective, if you ignore the splinters...",
		ARMOR_SANITY = "I REALLY don't like this. It's like those shadow hands...",
		ASH =
		{
			GENERIC = "Future Maxwell, if I get my way.",
			REMAINS_EYE_BONE = "I'm so sorry, Chester...",
			REMAINS_THINGIE = "...",
		},
		AXE = "Just looking at this makes my neck hurt... but it's effective.",
		BABYBEEFALO = "Aww, it's so cute!",
		BACKPACK = "Now I can carry more stuff!",
		BACONEGGS = "Delicious!",
		BANDAGE = "Crude, yet effective.",
		BASALT = "I'm not sure ANYTHING can break this.",
		BEARDHAIR = "...Is this human hair?",
		BEDROLL_STRAW = "Finally, something to sleep on..",
		BEE =
		{
			GENERIC = "I HATE bees.",
			HELD = "I'm a bee keeper! Hehe. ...I need to get off this island.",
		},
		BEEBOX =
		{
			FULLHONEY = "It's full of honey now!",
			GENERIC = "This is where the bees live.",
			NOHONEY = "There's nothing but bees in it.",
			SOMEHONEY = "There's SOME honey, but not enough..",
		},
		BEEFALO =
		{
			FOLLOWER = "Aww! That's right buddy, follow Mama Wisteria!",
			GENERIC = "It's like a buffalo, but with more beef.",
			NAKED = "I'm sorry, friend! It'll grow back.",
			SLEEPING = "I wonder what Beefalo dream about?.",
		},
		BEEFALOHAT = "It's warm and cozy, but it smells.",
		BEEFALOWOOL = "I can make something warm out of this.",
		BEEHAT = "This should protect me from those bees.",
		BEEHIVE = "A colony of bees. I'll steer clear, thank you.",
		BEEMINE = "I am going to throw so many bees at Maxwell. SO MANY.",
		BEEMINE_MAXWELL = "REALLY? Bee mines?! What a jerk!",
		BERRIES = "These are edible! Thank goodness.",
		BERRIES_COOKED = "Roasted to perfection.",
		BERRYBUSH =
		{
			BARREN = "It's been picked clean.",
			GENERIC = "Oh! Berries!",
			PICKED = "If I wait, they'll grow back.",
		},
		BIRDCAGE =
		{
			GENERIC = "I can keep a pet bird in here!",
			OCCUPIED = "Hello, little songbird! I'll call you Wren.",
			SLEEPING = "Dream of freedom for us both, little darling.",
		},
		BIRDTRAP = "I hope I did this right...",
		BIRD_EGG = "It's better if it's cooked.",
		BIRD_EGG_COOKED = "A yummy, cooked egg!",
		BISHOP = "One of Maxwell's guardians...",
		BLOWDART_FIRE = "Hopefully as effective as it is unsafe.",
		BLOWDART_SLEEP = "I hope I'm pointing this the right way.",
		BLUEAMULET = "I feel calm but... so cold...",
		BLUEGEM = "It's ice cold!",
		BLUEPRINT = "I hope I'm reading these correctly. What could go wrong?",
		BLUE_CAP = "Raw, this SHOULD restore my health... at the cost of some sanity.",
		BLUE_CAP_COOKED = "Now it restores sanity, but it's harmful.",
		BLUE_MUSHROOM =
		{
			GENERIC = "This is a Blue Cap mushroom.",
			INGROUND = "I can't pick it right now.",
			PICKED = "It's been picked already!",
		},
		BOARDS = "Smooth and splinter free!",
		BOAT = "If only it could take me home.",
		BONESHARD = "Just looking at these makes me feel uncomfortable.",
		BONESTEW = "OH, it smells divine!",
		BUGNET = "I can catch bugs with this!",
		BUSHHAT = "If I can't see them, they can't see me...",
		BUTTER = "This BUTTER last me awhile.",
		BUTTERFLY =
		{
			GENERIC = "Oh! It's a butterfly!",
			HELD = "You're going to make some fine tonics.",
		},
		BUTTERFLYMUFFIN = "What has science done?",
		BUTTERFLYWINGS = "These have amazing restorative properties.",
		BUZZARD = "Thats one mean looking bird!",
		CACTUS = 
		{
			GENERIC = "What a prickly plant!",
			PICKED = "Down in the ground.",
		},
		CACTUS_MEAT_COOKED = "Theres a first for everything.",
		CACTUS_MEAT = "Mmm, nothing like a mouthfull of nails.",
		CACTUS_FLOWER = "Ooh! How lovely!",
		CAMPFIRE =
		{
			EMBERS = "Oh no! It's about to go out!",
			GENERIC = "Ah, much better.",
			HIGH = "It's going to spread at this rate!",
			LOW = "I need to add more fuel soon!",
			NORMAL = "Comfortable and safe.",
			OUT = "I'm not getting any more use out of this now.",
		},
		CANE = "This will speed me up!",
		CATCOON = "I've always wanted a cat! I could pass on the raccoon part though...",
		CATCOONDEN = 
		{
			GENERIC = "Where did the yarn come from.",
			EMPTY = "H-Hello? Anyone home?.",
		},
		CATCOONHAT = "Adorable, but at what cost?",
		COONTAIL = "I'M SO SORRY.",
		CARROT = "Gross, I hate raw carrots.",
		CARROT_COOKED = "Mmm, nice and tender!",
		CARROT_PLANTED = "Grow my darling, grow!",
		CARROT_SEEDS = "Carrot seeds!",
		CAVE_FERN = "Cavernous flora.",
		CHARCOAL = "Sweet, sweet fuel.",
        CHESSJUNK1 = "All that remains of some twisted chess piece.",
        CHESSJUNK2 = "Stupid clockwork monsters.",
        CHESSJUNK3 = "It got what it deserved!",
		CHESTER = "Here, Chester! Such a good boy!",
		CHESTER_EYEBONE =
		{
			GENERIC = "Is that a... bone?",
			WAITING = "I'm so sorry, Chester...",
		},
		COOKEDMANDRAKE = "It won't be screaming NOW.",
		COOKEDMEAT = "This smells wonderful!",
		COOKEDMONSTERMEAT = "Er... let's save this for a last resort.",
		COOKEDSMALLMEAT = "I'm going to need more than this!",
		COOKPOT =
		{
			COOKING_LONG = "I should do other stuff while I wait.",
			COOKING_SHORT = "This won't take long at all!",
			DONE = "All done!",
			EMPTY = "There's nothing in here.",
		},
		CORN = "I should pop it!",
		CORN_COOKED = "Tasty, but not very filling.",
		CORN_SEEDS = "I can grow corn now!",
		CROW =
		{
			GENERIC = "Creepy.",
			HELD = "It's just... staring.",
		},
		CUTGRASS = "Useful, but prickly... ouch!",
		CUTREEDS = "These were the most useful I could find.",
		CUTSTONE = "Smooth!",
		DEERCLOPS = "HOLY CRAP! RUN!",
		DEERCLOPS_EYEBALL = "Eyuck! Gross!",
		EYEBRELLAHAT =	"I'll look like a dork wearing this.",
		DEPLETED_GRASS =
		{
			GENERIC = "I should fertilize it if I want it to grow faster.",
		},
		DEVTOOL = "I'd rather not.",
		DEVTOOL_NODEV = "That doesn't look safe...",
		DIRTPILE = "Curious...",
		DIVININGROD =
		{
			COLD = "It's gone dead.",
			GENERIC = "This should lead me to what I need!",
			HOT = "OKAY, I got it! I'm close! Shut up!",
			WARM = "I'm going the right way.",
			WARMER = "Almost there...",
		},
		DIVININGRODBASE =
		{
			GENERIC = "What is that...?",
			READY = "It looks like it needs a key...",
			UNLOCKED = "Well... here goes...",
		},
		DIVININGRODSTART = "I guess I'm supposed to use this?",
		DRAGONFLY = "Talk about garden pests!",
		ARMORDRAGONFLY = "I guess I'm hot now? Ehh...",
		DRAGON_SCALES = "They feel nice...",
		DRAGONFLYCHEST = "Loot well spent!",
		LAVASPIT = 
		{
			HOT = "Rude!",
			COOL = "No manners what so ever.",
		},
		DRAGONFRUIT = "Oooh, this looks tasty.",
		DRAGONFRUIT_COOKED = "Cooked fruit!",
		DRAGONFRUIT_SEEDS = "I can grow that weird fruit now.",
		DRAGONPIE = "Mmm, fruit pie!",
		DRUMSTICK = "I'd prefer this cooked.",
		GLOMMER = "I like its little wings!",
		GLOMMERFLOWER = 
		{
			GENERIC = "I've never seen a flower like this before...",
			DEAD = "I think its sad that Glommer died...",
		},
		GLOMMERWINGS = "Flap no more, little Glommer wings.",
		GLOMMERFUEL = "Eww, throw it in a fire!",
		BELL = "A useless old bell.",
		STATUEGLOMMER = 
		{	
			GENERIC = "Oh! Thats a... um... thing?",
			EMPTY = "I feel that was a bit harsh.",
		},
		DRUMSTICK_COOKED = "Dinner!",
		DUG_BERRYBUSH = "Hm, I can replant this.",
		DUG_GRASS = "The grass is so rough here.",
		DUG_MARSH_BUSH = "Yep. That's a bush.",
		DUG_SAPLING = "Sorry, little guy!",
		DURIAN = "Oh, GROSS! It smells HORRIBLE!",
		DURIAN_COOKED = "Cooking it just made it worse!",
		DURIAN_SEEDS = "In case I want to grow a garden of stink, I guess.",
		EARMUFFSHAT = "They fit over my hat!",
		EGGPLANT = "Ooh, I love eggplant.",
		EGGPLANT_COOKED = "It reminds me of home.",
		EGGPLANT_SEEDS = "I can grow eggplant with this.",
		STUFFEDEGGPLANT = "Stuffed with awesome!",
		EARMUFFSHAT = "Cozy!",
		DECIDUOUSTREE = 
		{
			BURNING = "...Uh oh.",
			BURNT = "Poor tree.",
			CHOPPED = "How bad can I possibly be?",
			POISON = "Well, I'm officially spooked.",
			GENERIC = "It smells pleasant!",
		},
		ACORN = 
		{
		    GENERIC = "Plenty of acorns, but no squirrels..",
		    PLANTED = "It's a tree baby.",
		},
		ACORN_COOKED = "Roasted by the campfire.",
		BIRCHNUTDRAKE = "A mad little nut.",
		EVERGREEN =
		{
			BURNING = "...Uh oh.",
			BURNT = "Poor tree.",
			CHOPPED = "How bad can I possibly be?",
			GENERIC = "It smells pleasant!",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "...Uh oh.",
			BURNT = "Poor tree.",
			CHOPPED = "How bad can I possibly be?",
			GENERIC = "It's a tree baby.",
		},
		EYEPLANT = "Oh. Oh, that's creepy.",
		FARMPLOT =
		{
			GENERIC = "I should plant something here.",
			GROWING = "Grow, my sweet! Grow!",
			NEEDSFERTILIZER = "Hmm... I'm going to need some fertilizer for this.",
		},
		FEATHERHAT = "This is stupid.",
		FEATHER_CROW = "A crow feather. Usually used in darker mixtures...",
		FEATHER_ROBIN = "A robin feather! Such a pretty shade of red.",
		FEATHER_ROBIN_WINTER = "This belongs to a winter robin.",
		FEM_PUPPET = "S-She's trapped...!",
		FIREFLIES =
		{
			GENERIC = "If only I could catch them!",
			HELD = "Such a soft, comforting glow.",
		},
		FIREHOUND = "Eep! Nice doggy...",
		FIREPIT =
		{
			EMBERS = "Oh no! It's about to go out!",
			GENERIC = "Ah, much better.",
			HIGH = "It's going to spread at this rate!",
			LOW = "I need to add more fuel soon!",
			NORMAL = "Comfortable and safe.",
			OUT = "I'm not getting any more use out of this now.",
		},
		FIRESTAFF = "Willow would be proud.",
		FISH = "Mm, my favorite meal!",
		FISHINGROD = "There's poetic symbolism here, I KNOW it.",
		FISHSTICKS = "The name says it all.",
		FISHTACOS = "What's a taco?",
		FISH_COOKED = "Roasted to perfection. I can't wait!",
		FLINT = "Perfect for a spark!",
		FLOWER = "They smell, but these have plenty of uses!",
		FLOWERHAT = "Innocence given form.",
		FLOWER_EVIL = "It even SMELLS evil.",
		FOLIAGE = "It's just foliage.",
		FOOTBALLHAT = "I hate sports!",
		FROG =
		{
			DEAD = "Take THAT, you stupid frog.",
			GENERIC = "Those toads are a NASTY bunch.",
			SLEEPING = "They're almost tolerable when they're sleeping.",
		},
		FROGGLEBUNWICH = "Blech. Tastes muddy.",
		FROGLEGS = "The tendons are still active. Oop, there it goes!",
		FROGLEGS_COOKED = "There we go, no more jumping!",
		FRUITMEDLEY = "Yum, fruit!",
		GEARS = "I guess these are what keep them active.",
		GHOST = "Clever tricks, for a ghost!",
		GOLDENAXE = "But gold's a soft material...",
		GOLDENPICKAXE = "How this works on rock, I'll never know.",
		GOLDENPITCHFORK = "Gardening in style.",
		GOLDENSHOVEL = "I feel like this is meant to be looked at, not used.",
		GOLDNUGGET = "Oh! I know a masked merchant who would love this...",
		GRASS =
		{
			BARREN = "I should fertilize it.",
			BURNING = "Oops.",
			GENERIC = "It's prickly.",
			PICKED = "I'm not sure I can do much with this.",
		},
		GREEN_CAP = "Er... these are great, if you like crazy.",
		GREEN_CAP_COOKED = "Now it's the opposite of crazy.",
		GREEN_MUSHROOM =
		{
			GENERIC = "It's a Green Cap...",
			INGROUND = "I can't pick it like this.",
			PICKED = "It will grow back.",
		},
		GUNPOWDER = "Gunpowder.",
		HAMBAT = "Delighted to MEAT your acquaintance!",
		HAMMER = "I can fix it!",
		HEALINGSALVE = "Too bad I didn't know how to make this before I got into this mess...",
		HEATROCK =
		{
			COLD = "It's really cold.",
			GENERIC = "I can heat this up for warmth!",
			HOT = "Ooh! Hot, hot!",
			WARM = "Nice and toasty!",
		},
		HOMESIGN = "It says, 'Maxwell really smells like dogbuns'. Yes. Yes he does.",
		HONEY = "Sweet and delicious!",
		HONEYCOMB = "It's waxy.",
		
		HONEYHAM = "My favorite kind of ham.",
		HONEYNUGGETS = "Nuggets of... honey?",
		HORN = "I can hear the ocean! ...Wait.",
		HOUND = "H-Hounds...!",
		HOUNDMOUND = "Uh oh...",
		HOUNDBONE = "Yuck.",
		ICEBOX = "Perfect for keeping my food fresh!",
		ICEHAT = "I look like a fool.",
		ICEHOUND = "They take 'frostbite' to a whole new level.",
		INSANITYROCK =
		{
			ACTIVE = "Am I seeing things?",
			INACTIVE = "Nothing to see here.",
		},
		JAMMYPRESERVES = "Just like Mama used to make.",
		KABOBS = "Dinner on a stick!",
		KILLERBEE =
		{
			GENERIC = "Like a bee, but deadly.",
			HELD = "It won't sting me now!",
		},
		KNIGHT = "Yikes! It's a Knight!",
		KOALEFANT_SUMMER = "We'll be great friends!",
		KOALEFANT_WINTER = "He sure looks warm...",
		KRAMPUS = "Stay back, you big jerk!",
		KRAMPUS_SACK = "I've got his bag!",
		LEIF = "HOOOOLY CRAP!",
		LEIF_SPARSE = "L-LEAVE ME ALONE!",
		LIGHTNING_ROD =
		{
			CHARGED = "Ooh, pretty.",
			GENERIC = "Try and zap me now, Maxwell!",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "'Baaaah' yourself!",
			CHARGED = "It's charged and charging!.",
		},
		LIGHTNINGGOATHORN = "It's like a miniature lightning rod.",
		GOATMILK = "Milking goats is a lot harder than I thought.",
		LITTLE_WALRUS = "A tiny walrus!",
		LIVINGLOG = "I really don't like the look of this.",
		LOCKEDWES = "Oh my! Those statues have him trapped!",
		LOG =
		{
			BURNING = "Burn, log, buuuurn!",
			GENERIC = "That's a log, alright!",
		},
		MALE_PUPPET = "H-He's trapped...",
		MANDRAKESOUP = "It tastes better than it sounds.",
		MARBLE = "It's super heavy!",
		MARBLEPILLAR = "Beatiful.",
		MARBLETREE = "Wow, it's made of marble.",
		MARSH_BUSH =
		{
			BURNING = "Well, at least the thorns won't be there.",
			GENERIC = "It looks sharp.",
			PICKED = "Ouch! Thorns!",
		},
		MARSH_PLANT = "It's all prickly.",
		MARSH_TREE =
		{
			BURNING = "Oops.",
			BURNT = "It's nothing but charcoal now.",
			CHOPPED = "Ha! Cut YOU down to size, didn't I?",
			GENERIC = "I'd better not touch it!",
		},
		MAXWELL = "I really. REALLY. Hate him.",
		MAXWELLHEAD = "Blah, blah, blah, SHUT UP!",
		MAXWELLLIGHT = "That's not creepy.",
		MAXWELLLOCK = "It needs a key...",
		MAXWELLTHRONE = "Wow... I almost feel bad for him now.",
		MEAT = "I better cook this!",
		MEATBALLS = "A literal ball of meat. Delicious!",
		MEATRACK =
		{
			DONE = "It's ready!",
			DRYING = "It needs more time to dry out.",
			GENERIC = "I should hang up some meat here.",
		},
		MEAT_DRIED = "It makes a nice treat, anyway.",
		MERM = "What is THAT?!",
		MERMHEAD = "It's a fish stick! Heh...",
		MERMHOUSE = "Blech. All the moisture is making it rot.",
		MONSTERLASAGNA = "Nothing like hairy, gooey monster bits with noodles. Gross.",
		FLOWERSALAD = "Nothing like a nice salad.",
        	ICECREAM = "I missed ice cream so much!!",
        	WATERMELONICLE = "Watermelon, on ice!",
        	TRAILMIX = "You can thank Shodance.",
        	HOTCHILI = "I never much cared for spicy foods.",
        	GUACAMOLE = "You can barely taste the mole!",
		MONSTERMEAT = "Ew, it's got hair IN the meat...",
		MONSTERMEAT_DRIED = "Is it changing color...? Yuck!",
		MOOSE = "I'd like to touch its feathers, if it wasn't trying to kill me.",
		MOOSEEGG = "Oh man! I could make a big omelette, or a quiche, or big sunny side ups...",
		MOSSLING = "I was just kidding about the giant omelette thing!",
		BEARGER = "OH JEEZ ITS A HIKERS WORST NIGHTMARE!.",
		BEARGERVEST = "Welcome to hibernation station!",
		FEATHERFAN = "Nothing like dead animal feathers to cool you off in the summer.",
		GOOSE_FEATHER = "I could make a nice pillow out of these!",
		MOSQUITO =
		{
			GENERIC = "I HATE mosquitoes!",
			HELD = "Don't you dare suck my blood!",
		},
		MOSQUITOSACK = "The only good part about mosquitoes.",
		MOUND =
		{
			DUG = "I probably shouldn't have done that...",
			GENERIC = "Do these belong to other survivors...?",
		},
		NIGHTLIGHT = "Standing close to this makes me uncomfortable.",
		NIGHTSTICK = "Quite shocking indeed!",
		NIGHTMAREFUEL = "Nightmare fuel! What am I supposed to do with this?",
		NIGHTSWORD = "Make my fears a weapon...",
		NITRE = "This looks deadly.",
		ONEMANBAND = "This is silly!",
		PANDORASCHEST = "I feel opening this may be a poor decision.",
		PANFLUTE = "Too bad it isn't a violin.",
		PAPYRUS = "It works like paper.",
		PENGUIN = "Aw! Look at their little tuxedos!",
		PERD = "Oh no you don't! Hands off those berries!",
		PEROGIES = "These are so yummy!",
		PETALS = "Useful for a garland or some remedies, too!",
		PETALS_EVIL = "Oh, gross! They're sticky and they smell...",
		PHLEGM = "Eugh, I hope I don't get sick...",
		PICKAXE = "It's very pointy.",
		PIGGYBACK = "This feels wrong.",
		PIGHEAD = "Hang in there, fella.",
		PIGHOUSE =
		{
			FULL = "I wonder what pigs do in their homes...",
			GENERIC = "Well, it's a home! Can't afford to be picky out here.",
			LIGHTSOUT = "H-Hey! Let me in! Please!",
		},
		PIGKING = "Oof... so THAT'S where that smell was coming from.",
		PIGMAN =
		{
			DEAD = "Sorry! But you're dinner tonight.",
			FOLLOWER = "He's my friend now!",
			GENERIC = "A little dumb, but they mean well.",
			GUARD = "He looks mean!",
			WEREPIG = "EEP! Stay back!",
		},
		PIGSKIN = "A piggy posterior. The rump of a swine. ...It's a butt.",
		PIGTORCH = "They look like they're having fun, at any rate.",
		PINECONE = 
		{
		    GENERIC = "I used to cover these in seeds for squirrels.",
		    PLANTED = "Grow, my sweet!",
		},
		PITCHFORK = "Good for gardening. Or stabbing, if desperate.",
		PLANTMEAT = "Eww, it's all slimy.",
		PLANTMEAT_COOKED = "Well... it isn't raw now, at least.",
		PLANT_NORMAL =
		{
			GENERIC = "Yum! Vegetables!",
			GROWING = "Grow, my sweet! Grow!",
			READY = "They're ripe!",
		},
		POMEGRANATE = "I never quite learned how to eat these.",
		POMEGRANATE_COOKED = "It smells like a tiny pie.",
		POMEGRANATE_SEEDS = "I think you can eat these.",
		POOP = "It's just fertilizer, it's just fertilizer...",
		PUMPKIN = "Gross as it is, but it makes lots of good food!",
		PUMPKINCOOKIE = "Yay! Cookies!",
		PUMPKIN_COOKED = "It's actually pretty yummy cooked!",
		PUMPKIN_LANTERN = "I'll name you Jack.",
		PUMPKIN_SEEDS = "These are pretty great toasted over a fire.",
		PURPLEGEM = "Oh, how pretty.",
		RABBIT =
		{
			GENERIC = "Look at his fluffy feet!",
			HELD = "I'm sorry, little guy...",
		},
		RABBITHOLE = "Down, down, down...",
		RAINOMETER = "It tells me when rain is coming.",
		RAINCOAT = "Fight me, rain.",
		RAINHAT = "My head will be rain proof.",
		RATATOUILLE = "Vegetables. So many vegetables.",
		RAZOR = "Why did I build this?",
		REDGEM = "Ow, it's hot!",
		RED_CAP = "Careful! These are really poisonous.",
		RED_CAP_COOKED = "It isn't much better cooked...",
		RED_MUSHROOM =
		{
			GENERIC = "It's a Red Cap.",
			INGROUND = "I can't pick it like this!",
			PICKED = "It will grow back.",
		},
		REEDS =
		{
			BURNING = "Oops.",
			GENERIC = "They're reeds!",
			PICKED = "I can't use it like it is.",
		},
        RELIC = 
        {
            GENERIC = "It's furniture.",
            BROKEN = "Reminds me of my village...",
        },
        RUBBLE = "It's all smashed.",
		RESEARCHLAB = "I still have much to learn.",
		RESEARCHLAB2 = "I've still got more studying to do!",
		RESEARCHLAB3 = "It's giving off a dark, pulsing energy...",
		RESURRECTIONSTATUE = "It's my safety net.",
		RESURRECTIONSTONE = "I guess I should touch it?",
		ROBIN =
		{
			GENERIC = "A brightly colored robin.",
			HELD = "You'll be safe here, darling.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "How does it stand the cold?",
			HELD = "Ooh, it's so warm...",
		},
		ROBOT_PUPPET = "I-It's trapped...",
		ROCK_LIGHT =
		{
			GENERIC = "A crusted over lava pit.",
			OUT = "It's gone cool.",
			LOW = "The lava is cooling!",
			NORMAL = "I'd better steer clear of that!",
		},
		ROCK_ICE = 
		{
			GENERIC = "How'd that get here?",
			MELTED = "Splish splash.",
		},
		ROCK_ICE_MELTED = "Splish splash.",
		ICE = "They're all melty.",
		ROCKS = "They're rocks.",
        ROOK = "Another of Maxwell's cretins!",
        ROPE = "A last resort, I guess.",
		ROTTENEGG = "Ew! Why? Oh Why?!",
		SANITYROCK =
		{
			ACTIVE = "I wonder what these markings mean...",
			INACTIVE = "Where'd it go?",
		},
		SAPLING =
		{
			BURNING = "Oops.",
			GENERIC = "That looks useful!",
			PICKED = "Aw, it looks so sad...",
		},
		SEEDS = "I can cook these or use them to grow crops!",
		SEEDS_COOKED = "The only option now is to eat them.",
		SEWING_KIT = "Perfect for clothes or skin.",
		SHOVEL = "Dig a hole, dig a hole, dig a hole.",
		SILK = "It's cool and smooth.",
		SKELETON = "O-Oh no! I hope it wasn't someone I knew...",
		SKULLCHEST = "Spooky scary skele-chest!",
		SMALLBIRD =
		{
			GENERIC = "It's a sweet little songbird!",
			HUNGRY = "Are you hungry, dearest?",
			STARVING = "I hear you! Don't fret, I'll get you food.",
		},
		SMALLMEAT = "I should probably cook this.",
		SMALLMEAT_DRIED = "It gives me something to chew on, at least.",
		SPAT = "It's so... ugly.",
		SPEAR = "I probably shouldn't throw this...",
		SPIDER =
		{
			DEAD = "The only good spider is a DEAD spider! ...Excepting Warren.",
			GENERIC = "I HATE spiders!.",
			SLEEPING = "Be brave and step lightly, Wisteria...",
		},
		SPIDERDEN = "That is all kinds of nasty.",
		SPIDEREGGSACK = "Tons of tiny disgusting spiders!",
		SPIDERGLAND = "It's gooey and clings to the skin. Gross.",
		SPIDERHAT = "Get it off, get it off!",
		SPIDERQUEEN = "EEK! Hurry up and die already!",
		SPIDER_WARRIOR =
		{
			DEAD = "MUCH better!",
			GENERIC = "It's huge!",
			SLEEPING = "I'd rather just leave it alone...",
		},
		SPOILED_FOOD = "It'd be stupid to eat it now!",
		SANITYTHING = "Don't ask me how it works.",
		HEALTHTHING = "Tastes awful, but it works.",
		STATUEHARP = "How lovely... it's so out of place here.",
		STATUEMAXWELL = "OH, LOOK AT ME, I'M DUMB STUPID MAXWELL, RAHH RAHHH RARUGH, PBBBTTTT. Jerk.",
		STEELWOOL = "For all those tough to clean dishes I use.",
		STINGER = "It's a stinger! Ground to powder, it's a fine ingredient.",
		STRAWHAT = "It keeps the sun off of me!",
		SUNKBOAT = "It's too far out. I can't reach it.",
		SWEATERVEST = "Stylish and functional!",
		REFLECTIVEVEST = "Right back at you, sun!",
		HAWAIIANSHIRT = "I need a proper vacation.",
		TAFFY = "Hmm... I don't really like sweets.",
		TALLBIRD = "He doesn't look too friendly!",
		TALLBIRDEGG = "Should I eat it or hatch it?",
		TALLBIRDEGG_COOKED = "Yummy, fried monster egg.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "It's really cold. I need to heat it up!",
			GENERIC = "I'd like a companion!",
			HOT = "Maybe I'm overdoing it?",
			LONG = "This might take a while...",
			SHORT = "It looks like it will hatch soon.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Oh! There's an egg inside!",
			PICKED = "The nest is empty.",
		},
		TEENBIRD =
		{
			GENERIC = "He's growing up so fast.",
			HUNGRY = "Hungry again? I just fed you!",
			STARVING = "Alright, alright! I'll get you some food.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Phew, finally! I've had enough of this world.",
			GENERIC = "I wonder what these symbols mean?",
			LOCKED = "I need to unlock it somehow.",
			PARTIAL = "Eventually, I'll escape this hell.",
		},
		TELEPORTATO_BOX = "Strange, it's warm.",
		TELEPORTATO_CRANK = "I wonder what this goes to?",
		TELEPORTATO_POTATO = "It's like a clunky, metal potato.",
		TELEPORTATO_RING = "This is pretty, in a creepy sort of way.",
		TENT = "Home sweet home.",
		SIESTAHUT = 
		{
			GENERIC = "I haven't had a good nap in awhile.",
			BURNT = "This is the EXACT opposite of what I had in mind.",
		},
		TENTACLE = "Ewww, a tentacle!",
		TENTACLESPOTS = "Ewwwww.",
		TENTACLESPIKE = "I was on the receiving end of this once. Not fun.",
		TENTACLE_PILLAR = "It's shaking!",
		TENTACLE_PILLAR_ARM = "Hey, back off!!",
		TENTACLE_GARDEN = "What's all that noise?",
		TOPHAT = "This feels too big for me.",
		TORCH = "If only it lasted forever.",
		TRANSISTOR = "Couldn't have named it better myself.",
		TRAP = "It's a bit passive aggressive, but it'll work.",
		TRAP_TEETH = "Let's see anything get past this!",
		TRAP_TEETH_MAXWELL = "What kind of jerk leaves this lying around?",
		TREASURECHEST = "It's a little house for all my stuff.",
		TRINKET_1 = "They don't look like they're any good now.",
		TRINKET_10 = "Ewww! What am I supposed to do with these?",
		TRINKET_11 = "It's kind of creepy, really.",
		TRINKET_12 = "It's all dry and hard. Yuck.",
		TRINKET_2 = "It's poorly made and clogged with dirt.",
		TRINKET_3 = "Looks like trying to undo this is all for KNOT!",
		TRINKET_4 = "It's staring at me!",
		TRINKET_5 = "I wonder if it works?",
		TRINKET_6 = "Where did these come from?",
		TRINKET_7 = "I always found this game boring.",
		TRINKET_8 = "Someone was lucky enough to have a tub out here, I guess.",
		TRINKET_9 = "These look oversized for even my apron.",
		TRUNKVEST_SUMMER = "I feel bad, but it will be handy!",
		TRUNKVEST_WINTER = "The only thing better would be a nice campfire!",
		TRUNK_COOKED = "Looks like it'll be kind of chewy.",
		TRUNK_SUMMER = "Well, part of him is still cuddly.",
		TRUNK_WINTER = "It's soft and squishy!",
		TUMBLEWEED = "Draw!",
		UMBRELLA = "It's all tattered, but it works well enough.",
		WAFFLES = "WAFFLES!",
		WALL_HAY = "This doesn't look too sturdy...",
		WALL_HAY_ITEM = "These won't hold up for very long.",
		WALL_STONE = "This will keep me safe!",
		WALL_STONE_ITEM = "Oof... It's so heavy!",
		WALL_RUINS = "Bring on your worst, Maxwell!",
		WALL_RUINS_ITEM = "I'll sleep soundly with these around my camp.",
		WALL_WOOD = "It's better than hay... kind of.",
		WALL_WOOD_ITEM = "If only it were stronger.",
		WARG = "Bad dog! BAD DOG!",
		WALRUS = "L-Leave me alone! Go away!",
		WALRUSHAT = "He's definitely more tolerable as a hat.",
		WALRUS_CAMP =
		{
			EMPTY = "It's uninhabited.",
			GENERIC = "Oh what I'd give for a roof over my head...",
		},
		WALRUS_TUSK = "Where's that merchant when you need him?",
		WASPHIVE = "I am NOT going near that.",
		WATERMELON = "I shall eat it whole!",
		WATERMELON_COOKED = "Cooked liquid, my favorite!",
		WATERMELONHAT = "My hair is going to get all sticky...",
		WETGOOP = "O-Oh... Oh my... was it not hot enough?",
		WINTERHAT = "Heehee, it's cute!",
		WINTEROMETER = "It tells me how cold it is.",
		WORMHOLE =
		{
			GENERIC = "Is it growling?",
			OPEN = "I wonder if it leads anywhere...",
		},
		WORMHOLE_LIMITED = "It looks sick... I don't know if it can take me back again.",
		ACCOMPLISHMENT_SHRINE = "This seems pointless.",        		
		LIVINGTREE = "I think it's watching me...",
		SKELETON_PLAYER =
		{
			MALE = "%s seems to have suffered death by %s...",
			FEMALE = "%s seems to have suffered death by %s...",
			ROBOT = "%s seems to have suffered death by %s...",
			DEFAULT = "%s seems to have suffered death by %s...",
		},
		ICESTAFF = "The cold never bothered me anyway.",

	},
	DESCRIBE_TOODARK = "I need more light!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Yuck! Was that the beak?",
	},
}
