return {
	"toad",
	"mushroomsprout_overworld",
	"sporecloud_toad",
	"deerclops_ground_fx",
	"root_spike",

	"uncompromising_rat",
	"ratpoison",
	--"ratpoisonbottle",
	"firemeteorwarning",
	"antlionwarning",
	"gasmask",
	"spiderqueencorpse",
	"flamegeyser",
	"lavae2",
	"mock_monsterwarningsounds",
	"mock_dragonfly",
	"lavaspit",
	"sandhill",
	"snowpile",
	"sand",
}