return {
	"toad",
	"mushroomsprout_overworld",
	"sporecloud_toad",
	"deerclops_ground_fx",
	"root_spike",

	"uncompromising_rat",
	"ratpoison",
	--"ratpoisonbottle",
	"firemeteorwarning",
	"antlionwarning",
	"gasmask",
	"spiderqueencorpse",
	"flamegeyser",
	"lavae2",
	"mock_monsterwarningsounds",
	"mock_dragonfly",
	"lavaspit",
	"sandhill",
	"snowpile",
	"sand",
	"snowgoggles",
	--"leechswarm", buggy atm
	"laitleech",
	"shockworm",
	"zaspberry",
	"snowmong",
	"firedrop",
	"bearger_sinkhole",
	"minimoonspider_spike",
}